### ISSUE TITLE
五期 - 针对「评论」、「喜欢」、「审核」制作新的通知。

### ISSUE THREAD

**Issue by LipYoung** [slimkit/plus#140]
目前系统消息接口设计中将 "点赞","评论", "待审核"等类型归属到了所有的系统消息中.导致了标题的问题以及相关的衍生问题.

暂定解决方案3期开发中,后台暂不处理该问题.4期将 "点赞""评论""待审核""@人"4个特殊种类从 系统消息中拆分出.

**Comment by medz** [comment]
- 评论独立
- 评论通知
- 喜欢独立
- 喜欢通知
- 审核独立
- 审核通知
- 其他通知消息
- 公告

**Comment by boxshadow** [comment]
完成第一版

**Comment by Jungle68** [comment]
功能需求

- 系统推荐分类下的资讯发布时需要推送给所有用户；
- 某个用户的内容或者评论被评论时需要收到推送消息；
- 某个用户被@时需要收到推送消息；
- 其他用户在某个用户的动态下申请评论置顶时需要收到推送；
- 其他用户在某个用户的资讯下申请评论置顶时需要收到推送；
- 其他用户在某个用户的帖子下申请评论置顶时需要收到推送；
- 某个用户的创建的圈子中，有成员发布帖子后并申请置顶时，需要收到推送；
- 某个用户的创建的圈子，有其他人员加入时，需要收到推送；
- 系统对某个用户（或全部用户）发送消息时，需要发送推送；

备注： 推送数据需要携带当前推送的功能类型（如资讯、评论置顶...等）
