### ISSUE TITLE
Node.js 方向

### ISSUE THREAD

**Issue by medz** [slimkit/plus#278]
是否确认「微服务化」，如果微服务话技术选型。不进行微服务，是否 Node 化？

## Node 化优势

1. 安装简易
2. 生态强大
3. 案例多
4. 技术相对门槛较低（如果会 Node）
5. 异步
6. 更高的负载

**Comment by zanjs** [comment]
nodejs is  Is the best language in the world！

**Comment by mutoe** [comment]
javascript 工程师表示支持 [滑稽][滑稽]

**Comment by westudiodev** [comment]
换成node门槛会低很多

**Comment by medz** [comment]
看时间五月前😂😂😂

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年8月23日，17:43，mutoe <notifications@github.com<mailto:notifications@github.com>> 写道：


javascript 工程师表示支持 [滑稽][滑稽]

**Comment by westudiodev** [comment]
大神，何不试试nodejs呢？我们已经让自己的php程序员转全站了（vue+node），php已经年事已高，node正春风少年
