### ISSUE TITLE
【发现-圈子-帖子详情】举报帖子后，后台举报管理没有举报信息

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#279]
### 描述:

举报帖子后，后台举报管理没有举报信息

**Comment by huhaophp** [comment]
@LMTcancan
 #### 后台圈子管理：基础设置可以设置举报处理
- 设置仅圈主 则圈主在移动端可以看到。
- 设置仅平台管理员 则平台可以在后台举报查看。

**Comment by shixinzi** [comment]
现在圈子的安装包都安装不了，删除了？
