### ISSUE TITLE
安卓APP分享到微信朋友圈无效（回答测试）

### ISSUE THREAD

**Issue by itb10why** [slimkit/plus#293]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:可以分享到朋友圈。但是朋友打不开。
跳出的是404H5页面。
是没有贯通吗？

### Fixed step:

- [ ] fixed.

**Comment by boxshadow** [comment]
问题将在15号发布的版本中统一修复完整
