### ISSUE TITLE
后台扩展部分目前发现动态管理，音乐这两个模块打开会报错

### ISSUE THREAD

**Issue by cruelwolfking** [slimkit/plus#302]
### 动态管理模块错误提示：
`"Class Zhiyi\Component\ZhiyiPlus\PlusComponentFeed\AdminControllers\HomeController does not exist"`

### 音乐模块打开错误提示：
`Class Zhiyi\Component\ZhiyiPlus\PlusComponentMusic\AdminControllers\HomeController does not exist`

**Comment by medz** [comment]
感谢反馈
