### ISSUE TITLE
【消息-审核-未读数】圈子加入申请，实际条数为 0 ，返回条数为 6

### ISSUE THREAD

**Issue by icepring** [slimkit/plus#310]
**Describe the bug**
圈子加入申请，实际条数为 0 ，返回条数为 6

**Expected behavior**
https://tsplus.zhibocloud.cn/api/v2/user/counts ，这个接口

**Desktop (please complete the following information):**
 - OS: [e.g. ANDROID]

**Comment by medz** [comment]
新通知开始写后开始解决通知问题，在新通知优化任务启动前不处理所有的通知问题，除非影响了使用才处理
