### ISSUE TITLE
[1.9] feat: Add Docker support

### ISSUE THREAD

**Issue by medz** [slimkit/plus#311]
- [ ] `slimkit/plus:Y.Z-full` (`Nginx`、`MySQL`、`php:7.2-fpm`、`Memcached`)
- [x] `slimkit/plus:Y.z-php-fpm` (`php:7.2-fpm`)
- [ ] `slimkit/plus:Y.Z-apache` (`php:7.2-apache`)
- [ ] `slimkit/plus:Y.Z-nginx` (`Nginx`、`php:7.2-fpm`)

**Comment by westudiodev** [comment]
docker现在可以测试吗？

**Comment by medz** [comment]
可以，已经提供 preview-fpm tag 了。

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年7月19日，16:03，westudiodev <notifications@github.com<mailto:notifications@github.com>> 写道：


docker现在可以测试吗？

**Comment by medz** [comment]
@westudiodev https://hub.docker.com/r/slimkit/plus/
