### ISSUE TITLE
动态当只有一张图时，位置没有居中，而是偏向左侧。

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#320]
![wechatimg943](https://user-images.githubusercontent.com/33219803/42875858-79971c06-8ab7-11e8-8b09-0ed9adc264ed.png)

**Comment by medz** [comment]
需求就是如此的😂😂😂你去骂你截图里面的李老板 这个是他想要的！

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年7月18日，18:24，westudiodev <notifications@github.com<mailto:notifications@github.com>> 写道：


[wechatimg943]<https://user-images.githubusercontent.com/33219803/42875858-79971c06-8ab7-11e8-8b09-0ed9adc264ed.png>

**Comment by westudiodev** [comment]
哦，原来是这样的。我看到你们的设计图，都是居中的。所以提个醒。
