### ISSUE TITLE
小米8录制视频UI无法正常操作

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#322]
在小米8手机录制短视频，顶部的控件被遮挡，点击完成按钮，画面闪烁。随后会出现内存溢出提示。
![wechatimg118](https://user-images.githubusercontent.com/33219803/42930026-6e6fe9ae-8b6e-11e8-9c86-d15bc3d2d2b1.jpeg)
![wechatimg946](https://user-images.githubusercontent.com/33219803/42930169-def96d44-8b6e-11e8-8c70-b8a2078c19f0.png)

**Comment by Jungle68** [comment]
@westudiodev  已查收，感谢反馈
