### ISSUE TITLE
yarn run prod 报错 cross-env

### ISSUE THREAD

**Issue by godblessu** [slimkit/plus#325]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/4978287/42998168-d1182b9c-8c4b-11e8-9eb4-52839e501bdf.png)

**Comment by godblessu** [comment]
yarn run dev 没有出现问题， 头疼了好久 百度了好久 均为解决

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/43042660-fa7e9cb2-8db5-11e8-85f5-3027f5cd42a2.png)
上传日志

**Comment by godblessu** [comment]
@medz 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node-8/bin/node',
1 verbose cli   '/usr/local/node-8/bin/npm',
1 verbose cli   'run',
1 verbose cli   'production' ]
2 info using npm@6.2.0
3 info using node@v8.11.3
4 verbose run-script [ 'preproduction', 'production', 'postproduction' ]
5 info lifecycle @~preproduction: @
6 info lifecycle @~production: @
7 verbose lifecycle @~production: unsafe-perm in lifecycle true
8 verbose lifecycle @~production: PATH: /usr/local/node-8/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/wwwroot/www.liaosm.com/node_modules/.bin:/home/wwwroot/www.liaosm.com/node_modules/.bin:/home/wwwroot/.config/yarn/link/node_modules/.bin:/home/wwwroot/www.liaosm.com/node_modules/.bin:/home/wwwroot/.config/yarn/link/node_modules/.bin:/home/wwwroot/.yarn/bin:/usr/local/node-8/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/node-8/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/node-8/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/node-8/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/php7.1/bin
9 verbose lifecycle @~production: CWD: /home/wwwroot/www.liaosm.com
10 silly lifecycle @~production: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
11 silly lifecycle @~production: Returned: code: 1  signal: null
12 info lifecycle @~production: Failed to exec production script
13 verbose stack Error: @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/node-8/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/node-8/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /home/wwwroot/www.liaosm.com
16 verbose Linux 3.10.0-514.26.2.el7.x86_64
17 verbose argv "/usr/local/node-8/bin/node" "/usr/local/node-8/bin/npm" "run" "production"
18 verbose node v8.11.3
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 1
23 error Failed at the @ production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by medz** [comment]
你的错误无法排查，持续集成测试了很多次无此错误～

**Comment by medz** [comment]
https://circleci.com/gh/slimkit/plus/3618 给你参考

**Comment by godblessu** [comment]
@medz 网页打不开呢

**Comment by medz** [comment]
@godblessu 要翻墙

**Comment by godblessu** [comment]
@medz 收到

**Comment by godblessu** [comment]
@medz 问题解决了 
https://github.com/JeffreyWay/laravel-mix/issues/1304
![image](https://user-images.githubusercontent.com/4978287/43075793-6ea3aff2-8eb4-11e8-8a07-7a774dd8ab9a.png)
