### ISSUE TITLE
[android] IM模块更改群聊名称后返回群聊界面显示“该用户已被删除”

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#326]
[android] 群聊更改群名称后返回群聊界面显示“该用户被删除”
version：v1.8.3.0713
截图：
![wechatimg953](https://user-images.githubusercontent.com/33219803/43070743-37dcad86-8ea3-11e8-9458-baba0f8e5aac.png)

**Comment by Jungle68** [comment]
已修复
