### ISSUE TITLE
用户需求建议： 评论界面把回复聚合在原评论下方，同时增加点赞按钮

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#328]
现在的布局，回复很难找到原评论，特别是评论多的时候，很不方便
用户需求建议：
把回复聚合在原评论下方，同时增加点赞按钮
参考下图：
<img width="839" alt="screen shot 2018-07-25 at 19 36 41" src="https://user-images.githubusercontent.com/33219803/43198737-46401f5c-9042-11e8-9495-4d8da4a3f529.png">

**Comment by medz** [comment]
评论不是重点

**Comment by medz** [comment]
换句话说，楼中楼是我们否定了的方案～
