### ISSUE TITLE
【后台-钱包管理-流水】使用第三放支付成功之后后台状态仍然显示是等待

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#331]
## 配图
![image](https://user-images.githubusercontent.com/30249193/43375554-557aa83a-93e8-11e8-946c-e9fc201a5a38.png)

**Comment by zuoaihua** [comment]
同样问题，充值完后，积分和余额没有增加，充值状态   等待

**Comment by medz** [comment]
支付场景，pc，还是 app
