### ISSUE TITLE
建议将api和admin分成两个独立项目

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#332]
现在api和admin揉在一起。一个用laravel开发一个用vue开发。项目结构比较复杂，不利于维护。
建议，把api和admin分离开独立项目。这样便于以后维护。

**Comment by westudiodev** [comment]
推荐几个快速admin框架：

[vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)
[vue-element-admin](https://github.com/iview/iview-admin)
希望有所帮助

**Comment by medz** [comment]
与产品和商务要的相反，本来想分开的，但是他们要迁就傻逼用户，全部做在一起！
