### ISSUE TITLE
用户需求建议-动态右上角加入话题图标

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#334]
用户需求建议：
在动态UI的右上角增加话题UI入口，会方便很多
<img width="846" alt="screen shot 2018-08-06 at 17 04 40" src="https://user-images.githubusercontent.com/33219803/43707566-02dc9648-999b-11e8-9657-b85a82042dce.png">

**Comment by Jungle68** [comment]
个性化入口可以自定义哈
