### ISSUE TITLE
用户需求建议-帖子同步·

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#342]
优化建议：
增加来源标志，
类似广告标识
点击“阅读全文”直接跳入帖子详情页（而不是进入动态详情页）
<img width="847" alt="screen shot 2018-08-15 at 19 41 12" src="https://user-images.githubusercontent.com/33219803/44146692-623cf20c-a0c3-11e8-931b-684611e58563.png">

**Comment by medz** [comment]
这个需求直接 Pass(vt.)

**Comment by medz** [comment]
vt.pass 愿意，不符合 ts+ 动态需求和分离需求

**Comment by medz** [comment]
原因2: 正在制作转发到动态功能

**Comment by westudiodev** [comment]
如果动态模块和圈子模块完全分开，互不干扰，倒也不容易混淆。

**Comment by westudiodev** [comment]
同步倒动态这个功能本身就有些鸡肋。用处不大，还容易让人费解。如果能通过选项取消改功能也不失一种好的处理方法。

**Comment by westudiodev** [comment]
同步到动态这个功能本身就有些鸡肋。用处不大，还容易让人费解。如果能通过选项取消改功能也不失一种好的处理方法。
