### ISSUE TITLE
[2.0] 转发功能

### ISSUE THREAD

**Issue by medz** [slimkit/plus#343]
![ts](https://user-images.githubusercontent.com/5564821/44257019-6837eb00-a23d-11e8-9f05-3a27deb3c16a.png)

**Comment by medz** [comment]
后端开发完成

**Comment by 863324395** [comment]
帖子可以从A圈子转发到B圈子吗？

**Comment by 863324395** [comment]
圈子  问答 资讯 都是 唯一 只能转发到动态吗？ 还是可以选择性的转发到  圈子  问答  动态  任一模块？
