### ISSUE TITLE
我本地部署的BUG，将vue.js将三个等于号改成两个等于号就不会报错了

### ISSUE THREAD

**Issue by zhuangguiyang** [slimkit/plus#345]
第一次玩github，和提交issue，请见谅！
问题：部署项目时，发现我本地和线上linux系统又很多BUG ,因为就是做if else判断时用了三个等于号（===），倒是项目执行的结果，只会执行else，然后我将三个等于号改成了两个就可以正确显示了，例如
![image](https://user-images.githubusercontent.com/30619185/44394185-2f638300-a569-11e8-9373-c09a77a3c3e5.png)
![default](https://user-images.githubusercontent.com/30619185/44394193-35596400-a569-11e8-8ad4-a1e7f8352aba.png)

**Comment by zhuangguiyang** [comment]
这个项目还有好多好多的地方都是因为这个原因？？所以不懂了

**Comment by medz** [comment]
@mutoe 你的 https://github.com/slimkit/plus-small-screen-client 的锅！！！

**Comment by zhuangguiyang** [comment]
那么我应该怎么做才能解决呢？？我的项目开源版本和公司的授权版本都有这个问题

**Comment by zhuangguiyang** [comment]
@mutoe  你好，请问我应该怎么解决才好？？

**Comment by mutoe** [comment]
@zhuangguiyang fixed 
问题原因未知 体验站线上无此问题
