### ISSUE TITLE
等于（==）和全等于（===）的问题？？

### ISSUE THREAD

**Issue by zhuangguiyang** [slimkit/plus#347]
![image](https://user-images.githubusercontent.com/30619185/44440423-941aee00-a5fa-11e8-94e3-5ec05fc9e98d.png)
![Uploading image.png…]()
![Uploading 2.png…]()

因为你们的代码都是用全等于的，导致这三个判断都没有效果

**Comment by medz** [comment]
同类型问题你能不能在之前的 issue 进行回复？你不可能每次都 new issue 吧～

**Comment by medz** [comment]
而且，我给你说了，h5 的问题到 https://github.com/slimkit/plus-small-screen-client 去。。。。

**Comment by zhuangguiyang** [comment]
@medz 这个是后台的资讯模块啊，不是h5

**Comment by medz** [comment]
刚编译完，测试没有这个问题

**Comment by zhuangguiyang** [comment]
@medz 大哥，我知道你们那边没有这个问题，而我这边是真实有，所以才询问可能是什么原因？？，会不会是我这边安装少了扩展或者一些乱七八糟的事情？我在群上问，群主让我来提交issue

**Comment by medz** [comment]
所以排查呀～ 我们这边没法排查，你可以自行排查呀～

**Comment by medz** [comment]
你不能所有的问题都依赖别人呀，debug 能力是程序员的基本功～ 我们这边可以排查，前提是复现了才能，而现在只有你有，我们无法复现，其他用户也没有这个问题，所以只能你自己 debug 了～
