### ISSUE TITLE
[2.0] 圈子优化

### ISSUE THREAD

**Issue by medz** [slimkit/plus#348]
![5-1- -](https://user-images.githubusercontent.com/5564821/44445057-34304180-a612-11e8-84d4-8c8039b9846c.png)
![5-2- - -](https://user-images.githubusercontent.com/5564821/44445058-34304180-a612-11e8-8dd3-91e7eb5ece59.png)
![5-3- -](https://user-images.githubusercontent.com/5564821/44445059-34304180-a612-11e8-80ef-11e33d29603c.png)
![11-](https://user-images.githubusercontent.com/5564821/44445060-34c8d800-a612-11e8-9d5c-560bc8c7eb5c.jpg)
![12-](https://user-images.githubusercontent.com/5564821/44445061-34c8d800-a612-11e8-8876-5ba5ab3a5747.jpg)
![21- - -](https://user-images.githubusercontent.com/5564821/44445063-35fa0500-a612-11e8-9499-f7573717db4f.jpg)
![24-](https://user-images.githubusercontent.com/5564821/44445064-35fa0500-a612-11e8-96b5-f92137dc5060.jpg)
![32- -](https://user-images.githubusercontent.com/5564821/44445065-36929b80-a612-11e8-8aba-0a24c0db8fe8.jpg)
![33- -](https://user-images.githubusercontent.com/5564821/44445067-36929b80-a612-11e8-832f-8f16f1e5dd49.jpg)
![34-](https://user-images.githubusercontent.com/5564821/44445068-36929b80-a612-11e8-86ee-f1cb941f8e3f.jpg)
![ts 2 0](https://user-images.githubusercontent.com/5564821/44445069-372b3200-a612-11e8-92f4-ccbf25b4d17a.png)

**Comment by medz** [comment]
## 创建圈子创建对应的群聊

**Comment by westudiodev** [comment]
圈子首页如果能更美观些就更好了。

**Comment by medz** [comment]
后端开发完成
