### ISSUE TITLE
iOS 1.9.1 (build 21) 版聊天模块，左上角群列表刷新或点击某个群有时会闪退

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#349]
**Describe the bug**
iOS 1.9.1 (build 21) 版聊天模块，左上角群列表刷新或点击某个群有时会闪退

**To Reproduce**
1. Go to '聊天模块'
2. Click on '.左上角群列表
3. 刷新或点击某个群
4. 有时会闪退

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jungle68** [comment]
已修复
