### ISSUE TITLE
钱包和积分的逻辑

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#352]
假设A公司作为运营主体：
1、钱包、积分均可充值，钱包和积分可互相转换（这设计很好，有效规避了苹果商店的问题）
2、假设用户B通过支付宝充值100元，支付宝扣除手续费0.6元，A公司账户实得99.4元，B用户得到积分10000分。
3、B用户对积分进行提现，提现10000分，换算为人民币100元（不知提现支付宝是否有手续费，假设没有），则A公司账户需支付B用户100元，可A公司从B这里明明只得到了99.4元，这样岂不是要亏损？

建议：
1、用户之间互相打赏，平台可抽成，如甲打赏乙100积分，乙实得80积分，平台得20积分；
或2、提现设置转换比例，如甲提现10000积分，但是只能转换为80元。

第一种更好，因为从公司财务账面确认营业收入的角度，用户打赏行为发生时就可以确认了，而不是要等到提现。

**Comment by Jungle68** [comment]
@Godkillme  感谢反馈，已经提交反馈内容
