### ISSUE TITLE
app注册账号时默认手机注册可能会更符合中国人习惯

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#356]
**Describe the bug**
手机端注册账号时，默认是通过邮箱注册，可能会不符合国人习惯。

**To Reproduce**
1. Go to '登录/注册UI'
2. Click on '注册按钮'
3. See 默认显示的是邮件注册

**Expected behavior**
默认为手机注册UI，点击右上角的邮箱注册图标可以切换成通过邮件注册。

**Screenshots**
N/A

**Additional context**
这个虽然不是bug，但也不能算是新特性需求，所以暂且在这里发布。如有不妥请见谅。

**Comment by Jungle68** [comment]
@westudiodev  感谢建议，已提交反馈

**Comment by 21zv** [comment]
Android 2.1版 已经优化。可以关闭这个issue
