### ISSUE TITLE
关于 资讯 投稿 文章 名称不统一的问题

### ISSUE THREAD

**Issue by 863324395** [slimkit/plus#368]
在安卓端是 “我的文章” 在 IOS端 是 “我的投稿” 而在前端是资讯，这个能不能同意一下改为 “我的文章” 在前端是“文章”
![01](https://user-images.githubusercontent.com/40166823/44946726-5d33ac00-ae34-11e8-8743-19e9c2fcdb2e.jpg)
![02](https://user-images.githubusercontent.com/40166823/44946728-645aba00-ae34-11e8-9e18-409ac95573f1.jpg)

**Comment by medz** [comment]
66666
![image](https://user-images.githubusercontent.com/5564821/44946918-c4069480-ae37-11e8-83da-c90329c2a8ab.png)
但是wo我还发现了 iOS 上的 + 按钮存在一个像素级错误～

**Comment by 863324395** [comment]
+ 按钮存在一个像素级错误？ 正常的啊 没感觉错误

**Comment by 863324395** [comment]
这个 全部统一 名称 “我的文章”  “文章”  应该是更适合一些感觉.

**Comment by Jungle68** [comment]
@863324395  新版本已经修统一修改成我的文章了

**Comment by 863324395** [comment]
好的 赞

**Comment by 863324395** [comment]
@Jungle68 您是官方的是吗？
