### ISSUE TITLE
关于内部广告链接 跳转到 H5 的问题

### ISSUE THREAD

**Issue by 863324395** [slimkit/plus#372]
您好 官方 !
内部链接不能直接在APP端内部浏览 而是一定要跳转APP浏览？ 在APP 内部浏览这样是不是更好一些.
 
 
![001](https://user-images.githubusercontent.com/40166823/45103276-20ccbc80-b162-11e8-8092-0c691663bc4b.png)

**Comment by medz** [comment]
2.0 待发布版本中已移除！
