### ISSUE TITLE
用户需求建议-动态发布结果提示

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#379]
现在的方案：（我自己的亲身体验）
发布动态成功以后，并没有一个明确的成功提示。使用起来心里总是担心是否发送成功，经常需要刷新列表多次以便确认真的成功了。容易患上强迫症。

用户需求建议：
发布动态以后对结果进行统一提示（像问答这样的）。这样可以避免用户强迫症

**Comment by medz** [comment]
虽然我同意也很赞同你的想法，我也对现在的提示很不爽，例如服务器有时候因为客户端 Bug 上传非法图片什么的导致发送失败，但是客户端并没有明显提示，我觉得发一条动态让用户等待一下子，挺好的。放慢节奏，哪怕还是做秒发，但是失败提示能更加友好也行！

***实际情况是，这是老板特意嘱咐这么做的，我们下面的人就算觉得不好也没办法！*

你是授权客户，你可以咋自己的版本中这样修改哟！我关闭 Issue 哈！
