### ISSUE TITLE
建议：希望调高文章、帖子等标题字数上限

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#380]
当前文章、帖子等标题字数上限为20个字，根本不够。微信公众号标题字数上限是32，百度百家、企鹅号等标题字数上限都是30，再看其他新闻标题，**随便找一个标题字数都是20字以上**了（如下图）。

虽然自己调一下字数上限也方便，但每次更新版本都要调一次也很麻烦，希望TS+官方能调一下，对用户贴心一点。

![default](https://user-images.githubusercontent.com/33575502/45789921-e5c79e80-bcb4-11e8-9a95-4d4d9da2728a.jpg)

**Comment by Jungle68** [comment]
@Godkillme  收到反馈，已提交反馈内容
