### ISSUE TITLE
【2.0兼容问题】- 问题集说明

### ISSUE THREAD

**Issue by Jungle68** [slimkit/plus#382]
- [x] 1.【管理后台-圈子-圈子管理】查看圈子信息出错
![image](https://user-images.githubusercontent.com/7939686/45801143-8d5cc500-bce5-11e8-8312-4b6b62b24cb5.png)

- [x] 2. 【管理后台-动态管理- 动态列表】有头像的用户信息，头像显示错误
![image](https://user-images.githubusercontent.com/7939686/45801184-a796a300-bce5-11e8-9528-6d1eaa449cbb.png)

- [x] 3. 修改圈子头像，提示Server Error

- [x] 4. 【我的圈子-待审核列表】-  已经被关闭的圈子显示在了审核列表，接口：
https://tsplus.zhibocloud.cn/api/v2/plus-group/user-groups?limit=15&offset=0&type=audit 
![image](https://user-images.githubusercontent.com/7939686/45803009-fd217e80-bcea-11e8-9679-1e589ec001a7.png)

- [x] 5. 圈子中最新回复的接口返回数据错误，没有按照最新回复返回数据，接口： https://tsplus.zhibocloud.cn/api/v2/plus-group/groups/3/posts?limit=15&offset=0&type=latest_reply

- [x] 6. 话题，取消关注话题接口，Server  Error  接口：
DELETE Request https://tsplus.zhibocloud.cn/api/v2/user/feed-topics/15

**Comment by medz** [comment]
问题 5 是新的回复机制，从现在开始的新数据才会正确返回～
