### ISSUE TITLE
用户需求建议-帖子同步改为转发至动态

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#388]
用户痛点：
帖子同步到动态，格式没了，内容被截断了，还时不时来个！[image](/xxxxxx/xxxx/xxx)
同步功能不知道有什么卵用。让人费解。

优化建议：
将同步至动态，换成转发至动态。
更简便，更好用
<img width="850" alt="screen shot 2018-09-23 at 23 38 25" src="https://user-images.githubusercontent.com/33219803/45929857-12680880-bf8a-11e8-8604-d52523dc1c9e.png">

**Comment by 21zv** [comment]
同步这个功能有画蛇添足之嫌。特别是现在有了app内转发功能以后。同步除了会增加额外的bug外还会让用户感觉费解

**Comment by medz** [comment]
已将同步更改为转发
