### ISSUE TITLE
Bug：PC端问答，Markdown引用的效果显示不正常

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#391]
PC端问答（其他如圈子等没有测试），Markdown引用的效果显示不正常，如下图：

![default](https://user-images.githubusercontent.com/33575502/45999665-e1e2b480-c0d8-11e8-8059-194e8c9c49ce.jpg)

**Comment by mutoe** [comment]
该问题已修复

https://tsplus.zhibocloud.cn/questions/986/answers/1297
