### ISSUE TITLE
2.0版本 bug［安卓］：问答－添加问答，设置引用内容 下面在添加 图片会不显示图片 如图：

### ISSUE THREAD

**Issue by 863324395** [slimkit/plus#392]
2.0版本 bug［安卓］：问答－添加问答，设置引用内容 下面在添加 图片会不显示图片 如图：

![screenshot_20180926-193730](https://user-images.githubusercontent.com/40166823/46077993-5e52c180-c1c5-11e8-9268-f21d97b8c41a.jpg)

**Comment by Jungle68** [comment]
@westudiodev  收到反馈

**Comment by Jungle68** [comment]
已修复
