### ISSUE TITLE
PC端- 动态 -  怎么看动态详情

### ISSUE THREAD

**Issue by 863324395** [slimkit/plus#399]
# 有人在问 在PC端怎么看动态详情

如果是有一条内容比较长的动态看不完，

那..那..那...要怎么进入到详情页看全部内容呢？不能以专业的角度看待用户......

谁能想得到要点那一只小的可怜的眼睛才能看详情 

![image](https://user-images.githubusercontent.com/40166823/46289270-22e83680-c5bb-11e8-8947-ba3226244a52.png)

**Comment by mutoe** [comment]
感谢反馈，已提入开发进程
