### ISSUE TITLE
用户需求建议-源代码未遵守编码规范的一些地方

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#400]
iOS源代码发现一些未遵守正常编码规范的地方。可能是工作太忙遗漏了。

issue:
文件名，项目名称很多地方出现空格或特殊字符（如+号）。
不符合一般编码规范，并且存在潜在解析危险

issue:
入口文件AppDeleguate拼写错误。常规为AppDelegate
用户优化建议：
尽量按照更规范的编码原则，避免空格、中文字符、特殊字符命名项目或文件
注意重要文件的单词拼写是否正确
这样能提高代码质量。

<img width="863" alt="screen shot 2018-10-04 at 12 28 09" src="https://user-images.githubusercontent.com/33219803/46452968-44227000-c7d1-11e8-96b5-bfb75b14a897.png">

**Comment by Jungle68** [comment]
@westudiodev  感谢反馈，已经提交工程师
