### ISSUE TITLE
PC端：问题详情页，无法显示回答

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#409]
PC端，问题详情页，如果该问题有回答，回答无法显示，显示“server error”，同时一直在加载。如下图：
<img width="1192" alt="bug" src="https://user-images.githubusercontent.com/33575502/46902244-2a310d80-cef4-11e8-96e3-38200a5cdcc5.png">

**Comment by mutoe** [comment]
@Godkillme 11月28日测试正常

![image](https://user-images.githubusercontent.com/9391981/49128010-8d3ffd80-f304-11e8-8713-7efe5bbb8e53.png)

**Comment by Godkillme** [comment]
2.1已经修复，可以close了
