### ISSUE TITLE
Android版动态单图尺寸偏差

### ISSUE THREAD

**Issue by 21zv** [slimkit/plus#417]
issue：
android单图尺寸有偏差

iOS版和H5单图都可以正常居中
<img width="854" alt="screen shot 2018-10-25 at 17 06 10" src="https://user-images.githubusercontent.com/24535957/47489172-90188000-d878-11e8-8734-f1f3e1ef3252.png">

**Comment by zhiyicx** [comment]
@21zv  我们这边显示正常，能否提供一下相关机型和版本号？

**Comment by 21zv** [comment]
miui 9.2, miui 10

**Comment by Jungle68** [comment]
宽度是通过图片宽度动态计算的，分辨率高的手机宽可能没有达到最大图片宽度，所以这并不是一个bug，这是正常的计算与现实

**Comment by westudiodev** [comment]
好的。原来不是bug。
