### ISSUE TITLE
[2.2] 程序优化内容

### ISSUE THREAD

**Issue by medz** [slimkit/plus#420]
## 系统设置-站点设置

- [x] ⾦金金币，默认开启
- [x] 打赏，默认开启，打赏选项:10，50，100
- [x] 匿匿名开关，默认开启
- [x] 匿匿名规则，默认⽂文字:”匿匿名规则，管理理后台‘系统设置-站点设置’中可配置“
- [x] 预留留昵称:root,admin

## 系统设置-标签

- [x] 包括⼀一个默认标签分类(测试)
- [x] ⼀一个默认标签(测试);

## ⽤用户中⼼心-⻆角⾊色管理理

- [x] 创始⼈人和普通⽤用户，默认勾选上 “签到、发布动态、以及后续新功能的权限”

## 积分设置-配置

- [x] 积分规则,默认⽂文字“积分规则，管理理后台’积分设置-配置‘中可配置”;
- [x] 积分提现规则，默认⽂文字:“积分提现规则，管理理后台’积分设置-配置‘中可配
置”
- [x] 积分充值规则，默认⽂文字:“积分充值规则，管理理后台’积分设置-配置‘中可配
置”;
- [x] 积分充值、提现开关 默认打开
- [x] 默认充值选项: 1，10，100，200，500，1000
- [x] 单笔最⼩小提现额度:100
- [x] 单笔最⾼高提现额度:1000000
- [x] 单笔最⼩小充值额度: 1
- [x] 单笔最⾼高充值的:1000000

## 存储设置-基础设置

- [x] ⽂文件⼤大⼩小: 默认值: 10 ，10485760
- [x] 默认MIME 类型: jpeg 、png 、gif
- [x] 图⽚片尺⼨寸设置:宽 10~4000 ⾼高 10~4000

## 动态管理理

- [x] 基础设置- 默认打赏开启
- [x] 付费开关- 默认开启 ， ⾦金金额 默认: 100 ，500， 1000， 收费⽂文字⻓长度 50

## 资讯 - 投稿配置

- [x] 默认开启认证投稿
- [x] 默认开启付费投稿，付费⾦金金额 1

## 签到应⽤用

- [x] 默认开启，奖励 1

## 问答应⽤用-基本信息

- [x] 默认开启
- [x] 申请精选默认⾦金金额:200
- [x] 围观⾦金金额默认:100
- [x] 匿匿名规则，默认:“匿匿名规则，管理理后台’问答应⽤用-基本信息‘中可配置”
- [x] 悬赏规则，默认:”悬赏规则，管理理后台’问答应⽤用-基本信息’中可配置”

## 管理理后台新增配置

- [x] 环信配置，⽬目前是在后端代码中配置的，需要在管理理后台增加填写地址和开 关;
- [x] 腾讯、微博、微信 三⽅方key配置，需要在管理理后台增加输⼊入项

**Comment by Jungle68** [comment]
# 配置相关调整

> 1. 以下说到的配置接口都是： `/api/v2/bootstrappers`
> 
> 2. 正确配置信息接口来源于：`https://tsplus.zhibocloud.cn/api/v2/bootstrappers`
> 
> 3. 测试配置信息部署的地址：`http://114.215.203.142:666`

### 用户中心

- [ ] 普通用户默认没有 `[feed] Delete Feed` 权限
- [ ] 三方配置信息缺少一个微信公众平台信息的配置，原来 `social.php`中的`wechat-mp`配置
 	```
 	'wechat-mp' => [
        'appid' => 'wx0000000000',
        'secret' => '2fdoskafw3o333llll'
    ]
    ```
    
    
### 积分配置

- [ ] 积分设置--配置 ，配置接口中返回的提现开关状态为开启，但是在管理后台显示未勾选
![image](https://user-images.githubusercontent.com/7939686/49135224-0cdbc580-f321-11e8-937f-7faa13afeb15.png)

- [ ] 积分设置--配置 ，显示 积分充值开关—开启，但是配置接口未返回开启状态，
![image](https://user-images.githubusercontent.com/7939686/49135351-67752180-f321-11e8-89d7-bbb034fbdaf2.png)
正常表现为： 有currency:recharge 字段，并在其中有open：true，IAP_only 可默认ture 也可false ,不做要求；
![image](https://user-images.githubusercontent.com/7939686/49135389-84a9f000-f321-11e8-829b-2f15b896d532.png)


### 资讯

- [ ] 资讯--投稿配置 ， 管理后台表现正常
![image](https://user-images.githubusercontent.com/7939686/49135480-c9ce2200-f321-11e8-82ab-b9359eeb3552.png)

但是配置接口返回的配置数据错误，正确数据如下图：正确的开关状态，已经正确的积分数据
![image](https://user-images.githubusercontent.com/7939686/49135526-e66a5a00-f321-11e8-926b-92844b8753bd.png)

- [ ] 资讯--资讯分类列表 ，需要一个默认的分类：默认分类

### 签到

- [ ] 签到，管理后台表现正常，但是配置接口返回数据错误
	管理后台显示样式：
![image](https://user-images.githubusercontent.com/7939686/49135643-46610080-f322-11e8-921d-ec01f75992b4.png)
	正确的配置接口数据应该是：balance 为管理后台配置是数据
	![image](https://user-images.githubusercontent.com/7939686/49135698-70b2be00-f322-11e8-8289-ebbbc26ab9d6.png)

### 问答

 - [ ] 当前匿名规则使用的是： 系统设置 - 站点设置  中的开关和你们规则文字
 ![image](https://user-images.githubusercontent.com/7939686/49135778-b8394a00-f322-11e8-85ce-9ce8a30952c3.png)
 	对应配置接口返回的数据信息：
 	![image](https://user-images.githubusercontent.com/7939686/49135889-00f10300-f323-11e8-9b77-e60bdd982dad.png)
 	问答中的匿名规则未生效，需要统一将系统设置中的调整到问答下面
 	





@medz

**Comment by medz** [comment]
你这个就是需求更改了呀～启动接口返回的就是以前也是这么返回的～签到返回的单位不一样！

**Comment by Jungle68** [comment]
### 系统设置

- [ ]  站点设置三处修改。将1 移动到问答中去； 将2和3删除
![image](https://user-images.githubusercontent.com/7939686/49195515-67792e00-f3c2-11e8-8e1d-0e5f00420502.png)

**Comment by Jungle68** [comment]
### 问答应用
- [ ]  专题管理， 需要一个默认专题： 默认专题
