### ISSUE TITLE
微信分享着陆页增加app下载栏

### ISSUE THREAD

**Issue by 21zv** [slimkit/plus#424]
H5端详情页增加app下载栏

<img width="585" alt="screen shot 2018-11-12 at 19 26 43" src="https://user-images.githubusercontent.com/24535957/48344750-ee36c700-e6b0-11e8-95f7-1c8b0f02876c.png">

**Comment by mutoe** [comment]
done
请参见 [SPA MobLink 说明文档](https://github.com/slimkit/plus/tree/master/resources/spa#%E8%90%BD%E5%9C%B0%E9%A1%B5%E5%BC%95%E5%AF%BC%E5%90%AF%E5%8A%A8%E4%B8%8B%E8%BD%BD-app)
