### ISSUE TITLE
提现接口500

### ISSUE THREAD

**Issue by Jungle68** [slimkit/plus#426]
**Describe the bug**
调用提现接口500错误

- 接口地址：https://tsplus.zhibocloud.cn/api/v2/plus-pay/cashes
- 服务器版本号：2.1.2

**Comment by medz** [comment]
具体错误是什么？

**Comment by medz** [comment]
因为试了很多次无法复现

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/48996076-9b1b4480-f185-11e8-8670-2b288e22bb32.png)
