### ISSUE TITLE
使用钱包余额充值积分接口错误提示“余额参数不合法”

### ISSUE THREAD

**Issue by Jungle68** [slimkit/plus#427]
**Describe the bug**

使用钱包余额充值积分，充值不成功，切提示错误

- 接口地址：https://tsplus.zhibocloud.cn/api/v2/plus-pay/transform
- 服务器版本： 2.1.1

![image](https://user-images.githubusercontent.com/7939686/48400643-e71bc180-e761-11e8-96a7-ba11f9c085c3.png)
管理后台配置的最小充值金额为 ：1 分
![image](https://user-images.githubusercontent.com/7939686/48400716-14686f80-e762-11e8-98b0-bc1d21c14a0f.png)

正确情况： 充值成功

**Comment by medz** [comment]
@Jungle68 后台位置
