### ISSUE TITLE
【系统消息- 打赏消息】-  打赏单位错误

### ISSUE THREAD

**Issue by Jungle68** [slimkit/plus#428]
**Describe the bug**
目前的打赏单位仍然写的是 ”元“，正确的应该是 `bootstrappers`接口返回数据中的 `currency_name`中的`name`

![image](https://user-images.githubusercontent.com/7939686/48405578-7aa6bf80-e76d-11e8-805f-b2ff1f42f4f7.png)
 
服务器版本： 2.1.2
接口地址： http://tsplus.zhibocloud.cn/api/v2/user/notifications?limit=15&offset=0&type=all

**Comment by medz** [comment]
Bug 转需求，需要将变量写入字符串中，前端展示替换为启动接口中的单位

**Comment by medz** [comment]
@Jungle68 牵扯到积分打赏逻辑相关，并且不知道乔老师这么写的～这个从长计议
