### ISSUE TITLE
【管理后台-认证管理-认证用户】进入到认证用户报错

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#432]
## 配图
![image](https://user-images.githubusercontent.com/30249193/48594364-34c74280-e98b-11e8-8345-f5fda536ada8.png)

**Comment by Jungle68** [comment]
@maanrry  提供具体信息，是编辑用户还是什么其他操作？ 如果是编辑，编辑的用户名是什么？

**Comment by medz** [comment]
@Jungle68 好歹告诉我是哪个服务器之类的。。。。一个截图就太水了～

**Comment by Jungle68** [comment]
@medz 
服务器版本： 2.1.2
测试地址： http://test-plus.zhibocloud.cn/admin#/package/9

操作步骤：

1. 登录测试服管理后台；
2.点击认证管理；

页面显示错误：
![image](https://user-images.githubusercontent.com/7939686/49280697-cc697c80-f4c5-11e8-984c-c7ad0712e154.png)
