### ISSUE TITLE
【后台管理-问答】悬赏规则无法保存

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#443]
后台管理-问答-基本信息，悬赏规则填写内容后，点击“提交”，提示已保存，但是刷新之后又变成空白。
<img width="766" alt="default" src="https://user-images.githubusercontent.com/33575502/48655404-45da8700-ea51-11e8-8519-8f5c4286211f.png">

**Comment by Jungle68** [comment]
@Godkillme  悬赏规则使用问答模块下的。温馨提示，后台配置相关正在做优化调整，敬请关注下次的更新
