### ISSUE TITLE
获取未读信息数据接口报错

### ISSUE THREAD

**Issue by Jungle68** [slimkit/plus#449]
**Describe the bug**
登录成功后，调用未读信息接口报错

**To Reproduce**
1. 登录账号：  七夜      123456
2. 调用接口 GET Request http://114.215.203.142:8001/api/v2/user/unread-count 
3. 得到错误信息
**Screenshots**
![image](https://user-images.githubusercontent.com/7939686/49070399-8662ad80-f266-11e8-9d67-bce9df8fcb26.png)

 - OS: [ Android ]
 - Version [ 2.1.2 ]
 - Sever Version [ 2.1.2 ]

**Comment by medz** [comment]
重新依赖安装
