### ISSUE TITLE
【Android】当提示账号已过期点击确定，不能正确跳转到登录UI

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#450]
【Android版2.1.1】当提示账号已过期点击确定，跳转到修改密码UI，必须点击后退图标三次后才能跳转到登录UI。
应该是直接跳转到登录UI
<img width="863" alt="screen shot 2018-11-28 at 18 49 42" src="https://user-images.githubusercontent.com/33219803/49146992-67cfe580-f33e-11e8-8145-c5bcc42674eb.png">

**Comment by Jungle68** [comment]
已修复
