### ISSUE TITLE
【管理后台-资讯-资讯列表】- 添加新的资讯报错

### ISSUE THREAD

**Issue by Jungle68** [slimkit/plus#453]
**Describe the bug**
在填写好内容后，点击保存按钮，右下角提示错误信息，但是错误信息被贼当无法查看。

**To Reproduce**
1. 登录管理后台；
2. 选择资讯；
3. 选择资讯列表；
4. 点击添加资讯；
5. 填写好资讯的内容，标题、摘要、分类、标签、封面图、正文后点击发布；
6. 右下角出现无法看到的错误提示。

**Screenshots**
![image](https://user-images.githubusercontent.com/7939686/49196498-19fec000-f3c6-11e8-8de4-d826bf04878b.png)

 服务器地址：http://test-plus.zhibocloud.cn 
 版本号： 2.1.2
 账号可私聊获取

希望：
 提示信息可以被看到

**Comment by medz** [comment]
没有复现
