### ISSUE TITLE
【PC】在动态列表上左右切换查看图片和在列表上展示，下载需要付费的图片仍然是高亮的

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#474]
## 服务器
正式服
## 账号信息
任意一个账号，测试时登录的账号：灯灯灯 123456
## 操作步骤
1.使用用户账号在移动端发布多张图片，将其中一张设置成下载付费
2.使用用户账号在pc端登录-查看该动态
## 结果及配图
在列表上和在列表切换查看时下载付费的图片仍然是高亮的
![image](https://user-images.githubusercontent.com/30249193/49421720-130fed00-f7cc-11e8-98a9-f52ebf700d3a.png)
![image](https://user-images.githubusercontent.com/30249193/49421727-1acf9180-f7cc-11e8-9994-346c35b1dfbb.png)
## 期望
做成和查看付费一样都是高斯模糊的

**Comment by Jungle68** [comment]
下载付费不做模糊
