### ISSUE TITLE
h5 附近的人最后并没有把定位信息存储在表: around_amaps 中

### ISSUE THREAD

**Issue by godblessu** [slimkit/plus#480]
![image](https://user-images.githubusercontent.com/4978287/49507381-4d0bec80-f8bb-11e8-8ce8-3cd2ae43120d.png)
缺少请求创建当前用户在高德地图中的自定义位置. 这个接口的功能

**Comment by godblessu** [comment]
@medz

**Comment by godblessu** [comment]
@mutoe 这个问题有修复么 修复我就pull 下

**Comment by mutoe** [comment]
@godblessu 已修复，感谢反馈😊
