### ISSUE TITLE
【后台】问答-回答管理根据具体的回答者id搜索时仍然显示所有有回答的问题

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#487]
## 服务器
测试服
## 账号信息
root
##操作步骤
使用管理员账号登录后台-点击问答应用-点击回答管理-输入回答者id（或者输入回答者昵称-点击要搜索的的用户者）-点击搜索
## 结果
仍然显示所有有回答的问题
![image](https://user-images.githubusercontent.com/30249193/49630978-413f3800-fa2b-11e8-9271-9f20071ea4cb.png)
## 期望
可以根据具体的回答者id搜索

**Comment by maanrry** [comment]
嗯嗯

**Comment by medz** [comment]
@maanrry 这叫效率😂，提了马上修复～

**Comment by medz** [comment]
先继续找 bug 提交吧～华军他要先筛选一遍，这个 issue 之后的等筛选完成后再修复
