### ISSUE TITLE
【后台】问答应用-回答管理筛选类型为普通问题时，仍然显示邀请悬赏的问题

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#490]
## 服务器
测试服
## 账号信息
root
## 操作步骤
使用管理员账号登录后台-点击问答应用-点击回答管理-类型筛选选择：普通问题-点击搜索
## 结果及配图
![image](https://user-images.githubusercontent.com/30249193/49632750-cd545e00-fa31-11e8-9b2e-692d7f50b606.png)

## 期望
搜索普通问题应该是除了悬赏问题和被采纳问题之外的回答

**Comment by medz** [comment]
这个是后台文案错误，选项应该是 `普通回答`
