### ISSUE TITLE
【后台】打赏管理当有数据时点击导出无法成功导出

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#496]
## 服务器
测试服
## 账号信息
root
## 操作步骤
使用管理员账号登录后台-点击打赏管理-筛选有打赏数据的（如筛选2018.10.01-2018.12.08的全部）-点击导出
## 结果及配图
导出失败。进入如下页面
![image](https://user-images.githubusercontent.com/30249193/49638393-fdf0c380-fa42-11e8-9682-a633525a7a3a.png)

## 期望
可以成功导出

**Comment by medz** [comment]
与 #497 重复
