### ISSUE TITLE
【PC】问答-问答详情页，问题描述已经全部显示出来了，仍然有“显示更多”字样

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#500]
## 示例网址
https://tsplus.zhibocloud.cn/questions/1031

## 配图
![default](https://user-images.githubusercontent.com/33575502/49714294-54e6da80-fc87-11e8-80f6-16b4827918b0.png)

## 期望
当问题描述已经全部显示出来之后，就不要显示“显示更多”的字样

**Comment by mutoe** [comment]
preview from test server http://test-plus.zhibocloud.cn/questions/23

**Comment by maanrry** [comment]
@Jungle68 已修复
