### ISSUE TITLE
【SPA】创建话题时点击返回，缺少放弃创建提示

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#501]
## 服务器
测试服

## 操作
1. 点击发现-话题
2. 点击右上角创建话题
3. 输入任意内容
4. 点击左上角返回

## 结果
直接返回到上一页

## 预期
1. 上传了封面图片或输入了标题、话题内容时，点击返回出现提示语
2. 未输入任何内容时，点击返回直接返回上一页
<img width="253" alt="image" src="https://user-images.githubusercontent.com/25689097/49841732-af9d4500-fdf3-11e8-97d3-3a4524230b0f.png">

**Comment by maanrry** [comment]
@Jungle68 已修复
