### ISSUE TITLE
【SPA】发现-话题详情，使用iPhone进入话题详情，关注按钮显示错误

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#503]
## 服务器
测试服

## 测试设备
iPhone 5s、iPhone 6s plus、iPhone 7

## 配图
<img width="212" alt="image" src="https://user-images.githubusercontent.com/25689097/49843089-e4f86180-fdf8-11e8-814e-c3e707c9963d.png">
<img width="211" alt="image" src="https://user-images.githubusercontent.com/25689097/49843144-1f61fe80-fdf9-11e8-88c6-74bf891a00fd.png">

## 预期
<img width="220" alt="image" src="https://user-images.githubusercontent.com/25689097/49843252-7ff13b80-fdf9-11e8-8b09-3e881cd2b7e4.png">

**Comment by maanrry** [comment]
@Jungle68 已修复
