### ISSUE TITLE
【SPA】话题-话题详情-发布动态，从话题详情发布动态，第一个默认话题可以被删除

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#505]
## 服务器
测试服

## 描述
从话题详情发布动态，第一个默认话题可以被删除

## 配图
![2dd24545-5951-4d84-b931-fb31b2e825f4](https://user-images.githubusercontent.com/25689097/49844836-6521c580-fdff-11e8-8074-6edc2e238dfa.png)

## 预期
从话题详情进入的发布页面，第一个默认话题没有删除按钮
![9881593b-5f0c-4b4f-a0d2-335f04943b8b](https://user-images.githubusercontent.com/25689097/49844839-66eb8900-fdff-11e8-9fff-5f041caa2cd4.png)

**Comment by maanrry** [comment]
@Jungle68 已修复
