### ISSUE TITLE
【SPA】话题-话题详情-发布动态，emoji没有被算入字数统计

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#506]
## 服务器
测试服

## 描述
发布动态时emoji没有被算入字数统计
输入emoji+文字、纯emoji，超过255仍然可以输入并且发布成功

## 配图
<img width="213" alt="image" src="https://user-images.githubusercontent.com/25689097/49845521-fe51db80-fe01-11e8-90e8-292ecb421f3d.png">

![36a379af-1a6d-46fa-87b8-462149828376](https://user-images.githubusercontent.com/25689097/49845410-969b9080-fe01-11e8-8792-eb28a8cb2f07.png)

## 预期
emoji也需要计算字数

**Comment by maanrry** [comment]
@Jungle68 已修复
