### ISSUE TITLE
【SPA】在首页或者话题详情收藏了动态后，在我的收藏列表没有该动态

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#507]
## 服务器
测试服

## 测试账号
18208167252    123456

## 描述
在首页或者话题详情收藏了动态后，提示收藏成功，但在我的收藏列表没有该动态

## 配图
<img width="223" alt="image" src="https://user-images.githubusercontent.com/25689097/49849362-20545980-fe14-11e8-99f7-28bba80337ad.png">

## 预期
<img width="214" alt="image" src="https://user-images.githubusercontent.com/25689097/49849370-277b6780-fe14-11e8-8766-d296e88c2775.png">

**Comment by maanrry** [comment]
@Jungle68 已修复
