### ISSUE TITLE
【SPA】话题-搜索话题，在iPhone上搜索图标位置偏移

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#508]
## 服务器
测试服

## 测试设备
iPhone 5s、iPhone 6s plus、iPhone 7

## 描述
1. 在iPhone上搜索图标位置偏移
2. 占位文字错误，应该是“搜索”

## 配图
<img width="212" alt="image" src="https://user-images.githubusercontent.com/25689097/49849564-167f2600-fe15-11e8-89a3-c4fbfe22ee46.png">

## 预期
<img width="295" alt="image" src="https://user-images.githubusercontent.com/25689097/49849554-08c9a080-fe15-11e8-92c9-518b32c9aff2.png">

**Comment by maanrry** [comment]
@Jungle68 已修复
