### ISSUE TITLE
【SPA】话题详情，点赞动态后在列表和详情文字字体颜色都不对

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#514]
## 服务器
测试服

## 配图
![a286bc0b-e58e-4b95-aa0d-140b87d64a7f](https://user-images.githubusercontent.com/25689097/49855953-acbd4700-fe29-11e8-81e1-d4ebb0d8e833.png)
![9c5f283d-c7c9-4ebe-8310-fa88a2c97dae](https://user-images.githubusercontent.com/25689097/49855954-adee7400-fe29-11e8-9a47-ddbd45ffa5bf.png)

## 预期
1. 在列表上点赞数量也要变红
2. 在详情页“喜欢”也要变红

**Comment by maanrry** [comment]
@Jungle68 已修复
