### ISSUE TITLE
【SPA】话题详情-动态详情，移动端发布的下载付费图片，在动态详情点击查看大图出现付费提示

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#515]
## 服务器
测试服

## 描述
移动端发布的下载付费图片，在动态详情点击查看大图出现付费提示
链接：http://test-plus.zhibocloud.cn/h5/feeds/99
（该动态最后两张图片）

## 配图
<img width="300" alt="image" src="https://user-images.githubusercontent.com/25689097/49856335-81872780-fe2a-11e8-85a3-1929e7da72c0.png">

## 预期
移动端发布的下载付费图片，作为免费图片处理，不需要付费

**Comment by maanrry** [comment]
@Jungle68 已修复
