### ISSUE TITLE
【SPA】话题-创建话题，有三处与设计图不符

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#516]
## 服务器
测试服

## 描述
1. 左上角取消按钮与设计图不符
2. 话题标题占位文字没有加粗
3. 话题内容字数统计位置不对

## 配图
![25cb6845-2cfa-4f70-9ee4-1a6059cf23b6](https://user-images.githubusercontent.com/25689097/49856654-58b36200-fe2b-11e8-8e8e-a626f71b542a.png)

## 预期
![ad5eee93-707b-443f-9092-748420abcb88](https://user-images.githubusercontent.com/25689097/49856699-77195d80-fe2b-11e8-9a71-25946f6bb738.png)

**Comment by maanrry** [comment]
@mutoe 缺少字数提示
![image](https://user-images.githubusercontent.com/30249193/50062096-19489500-01e0-11e9-8b09-2d7d93337c02.png)

**Comment by maanrry** [comment]
@Jungle68 已修复
