### ISSUE TITLE
【SPA】话题详情，当话题没有动态时，缺少缺省图

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#517]
## 服务器
测试服

## 描述
当话题没有动态时，缺少缺省图

## 配图
![b43ea804-bae2-46af-80c5-f3aed7db4d10](https://user-images.githubusercontent.com/25689097/49856776-b051cd80-fe2b-11e8-94a1-74617dc16de1.png)

## 预期
![e75e5a44-1cf2-4b4d-94da-71062f6f9e96](https://user-images.githubusercontent.com/25689097/49856782-b34cbe00-fe2b-11e8-912f-7c02dd203cd2.png)

**Comment by maanrry** [comment]
@Jungle68  已修复
