### ISSUE TITLE
【SPA】话题-搜索话题，输入不存在的搜索内容后再删除内容，推荐的热门话题列表会变为最新话题列表

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#518]
## 服务器
测试服

## 描述
输入不存在的搜索内容后再删除内容，推荐的热门话题列表会变为最新话题列表

## 操作
1. 进入搜索话题页面，默认显示推荐话题列表
2. 在搜索框输入不存在的话题
3. 删除搜索框所有内容

## 结果
列表显示为最新话题列表

## 配图
输入前：
![1fa34873-f953-4aa2-8700-f2746d67793b](https://user-images.githubusercontent.com/25689097/49859116-b8ad0700-fe31-11e8-83f8-b36b4bef2eed.png)

删除输入内容后：
![96a85595-41ed-49f2-81a0-599eda004a8a](https://user-images.githubusercontent.com/25689097/49859144-c3679c00-fe31-11e8-86c7-2a6c7c33911e.png)

## 预期
没有搜索内容时始终显示热门话题

**Comment by maanrry** [comment]
已修复
