### ISSUE TITLE
【SPA】话题详情，进入未关注的话题详情发布动态后点击关注话题，关注状态未变更

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#519]
## 服务器
测试服

## 描述
进入未关注的话题详情发布动态后点击关注话题，关注状态未变更

## 操作
1. 进入未关注的话题详情
2. 在该话题发布动态
3. 点击关注

## 结果
提示关注成功，但按钮状态未变更，关注数也没有增加

## 配图
<img width="213" alt="image" src="https://user-images.githubusercontent.com/25689097/49861266-71754500-fe36-11e8-8bb4-292919723067.png">

## 预期
1. 关注人数+1
2. 按钮变为“已关注”状态

**Comment by mutoe** [comment]
@LMTcancan 是在IPhone上复现的吗？我这里没有复现

**Comment by mutoe** [comment]
@medz 接口问题（安卓端也存在此问题）

## 复现过程
1. 在未关注的话题下发布动态
2. 关注话题 （`PUT` `/api/v2/user/feed-topics/19`）返回 204
3. 并未关注成功
