### ISSUE TITLE
【PC】我的钱包-充值，自定义充值金额，产生错误

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#520]
bug描述：【PC端】我的钱包-充值，选择”**自定义充值金额**“，提示错误“请选择或输入金额“。
<img width="894" alt="bug" src="https://user-images.githubusercontent.com/33575502/49877219-e741d680-fe5f-11e8-9194-12cb297ccb60.png">

**Comment by mutoe** [comment]
感谢反馈
