### ISSUE TITLE
2.2 Android

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#522]
2.2 Android版，圈子帖子和问答转发失败
![wechatimg1215](https://user-images.githubusercontent.com/33219803/49943480-fa69aa80-ff22-11e8-9e36-bb817ba3b8c2.jpeg)

**Comment by Jungle68** [comment]
@westudiodev  收到，感谢反馈

**Comment by Jungle68** [comment]
@medz 
## 补充错误信息：
1. 转发圈子报错：

  - 接口地址：`http://test-plus.zhibocloud.cn/api/v2/feeds`
  - 参数信息： ```{"feed_content":"转发圈子","feed_from":"4","feed_mark":"61544754950776","id":3,"images":[],"photos":[],"repostable_id":1,"repostable_type":"groups","topicListBeans":[],"topics":[]}```
  - 用户： 七夜
  - 错误信息：转发的资源类型不合法

  
2. 转发帖子报错：
	- 类型：`"repostable_type":"group-posts"`

3. 转发问题报错：
	- 类型：`"repostable_type":"questions"`
 
4. 转发回答报错：
	- 类型：` "repostable_type":"question-answers"`
