### ISSUE TITLE
【SPA】打赏自己的动态、帖子、回答、文章时，提示语一直不消失

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#525]
## 服务器
测试服
## 描述
选择自己的的动态、帖子、回答、文章，点击打赏，输入打赏金额-点击确认-输入密码（或不输入）
## 结果
提示成功，但是提示语一直不消失
![image](https://user-images.githubusercontent.com/30249193/50065499-c7106f80-01f1-11e9-9a1b-65c4dc2294a9.png)
## 期望
出现提示之后一会(最多几秒）就消失

**Comment by mutoe** [comment]
@maanrry 服务器不允许打赏自己发布的相关内容，改为隐藏自己的打赏按钮
