### ISSUE TITLE
【消息-审核消息】圈子相关的审核消息没有小红点提示

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#529]
## 服务器
测试服
## 操作步骤
场景一：用户A加入用户B的需要审核的圈子（私密圈和私密付费圈），用户B的消息-审核消息缺少小红点提示
场景二：用户A在用户B的圈子里发布了帖子1并且帖子置顶，用户B的消息-审核消息缺少小红点提示
场景三：用户A在用户B的帖子下评论了并且申请评论置顶，用户B的消息-审核消息缺少小红点提示
## 配图
![image](https://user-images.githubusercontent.com/30249193/50069836-c7673580-0206-11e9-948d-03db3e9a888f.png)
## 期望
上面三种场景消息-审核消息都应该有小红点，最好能判断哪个分类下有未读消息，点击审核消息的时候定位了该分类下（如文章评论置顶有未读消息，点击审核消息时置顶定位到文章评论置顶）

**Comment by mutoe** [comment]
服务端问题 暂不处理
