### ISSUE TITLE
【ADMIN】新注册的账号无法投稿成功

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#540]
## 服务器
正式服
## 操作步骤
1.选择三方、邮箱账号、手机账号注册新用户
2.点击发现-资讯-投稿
## 结果
投稿失败
![image](https://user-images.githubusercontent.com/30249193/50128886-cd662080-02b1-11e9-9c6f-527fa55515e0.png)
## 期望
可以投稿成功

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/50409564-779ff400-082e-11e9-817c-775dad8498a4.png)

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/50409574-9605ef80-082e-11e9-8393-5d0f14a31b54.png)

如果要修改默认，就提成需求！不要就挂一个 Bug 符号！
