### ISSUE TITLE
【ADMIN】转发圈子、帖子、问题、回答时发布失败

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#541]
## 服务器
测试服
## 操作步骤
场景一：用户账号登录后-->点击发现-圈子-->分享-->转发-->输入转发内容（或不输入）-->点击发布
场景二：用户账号登录后-点击发现-圈子-->点击任意一篇帖子，进入帖子详情（或者在圈子详情列表）-->点击更多（详情页点击分享、列表上点击更多）-->点击转发-输入转发内容（或不输入）-->点击发布
场景三：用户账号登录后-点击发现-问答-->点击任意一个问题，进入问题详情-->点击分享-->点击转发-->输入转发内容（或不输入）-->点击发布
场景四：用户账号登录后-点击发现-问答-->点击任意一个问题，进入问题详情-->点击任意一个回答-->点击分享-->点击转发-->输入转发内容（或不输入）-->点击发布
## 结果及配图
四个场景都发布失败
场景一配图：
![image](https://user-images.githubusercontent.com/30249193/50130704-e4107580-02b9-11e9-812b-7f3d08d864f1.png)
场景二配图：
![image](https://user-images.githubusercontent.com/30249193/50130620-677d9700-02b9-11e9-9ff6-0433e74e4b9d.png)
场景三配图：
![image](https://user-images.githubusercontent.com/30249193/50130720-f8547280-02b9-11e9-9ba7-2f3301fd4c4f.png)
场景四配图：
![image](https://user-images.githubusercontent.com/30249193/50130734-05716180-02ba-11e9-8767-8bf1feffdeac.png)
## 期望
可以都转发成功

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/50262572-f4a52500-044c-11e9-82b7-495798f32a92.png)
真他妈的够了～
