### ISSUE TITLE
【PC】PC端，点击动态首页左侧”排行榜“报错

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#543]
PC端，点击动态首页左侧”排行榜“报错，如图：
<img width="894" alt="2018-12-18 22 50 39" src="https://user-images.githubusercontent.com/33575502/50161791-b1956580-0317-11e9-8974-a5f5d9917442.png">
<img width="1218" alt="2018-12-18 22 51 39" src="https://user-images.githubusercontent.com/33575502/50161816-bb1ecd80-0317-11e9-9e10-0ef2b67c79ec.png">

**Comment by medz** [comment]
暂时没有复现～

**Comment by mutoe** [comment]
已修复
