### ISSUE TITLE
【PC】PC端-我的钱包-提现，无法获取支付宝图像&未获取钱包余额

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#549]
【PC】PC端-我的钱包-提现，存在2处问题：
1、提现金额，默认填充是“钱包余额2”，正确的应该是将钱包余额的金额写在这里吧。
2、选取提现方式下的支付宝图像未获取到，获取的图片是“pay_pic_zfb_on.png”，而PC的package里面的图片名称叫做“pay_pic_zfb.png”。

![bug](https://user-images.githubusercontent.com/33575502/50197299-73349080-0381-11e9-839f-870f1500c548.png)

**Comment by maanrry** [comment]
已修复
