### ISSUE TITLE
【pc】编辑圈子简介和圈子公告时使用了换行，但是在圈子详情没有显示出来

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#554]
## 服务器
测试服
## 操作步骤
1.点击自己的圈子，进入圈子详情
2.点击设置
3.编辑圈子简介和圈子公告，并且输入的文字内容之间使用换行，
   如：

         啦啦啦啦啦

          啦啦啦

         啦啦啦啦
4.点击提交
5.再次进入该圈子详情
备注数据连接：http://test-plus.zhibocloud.cn/groups/9
## 结果
圈子简介和公告没有显示换行格式
简介：
![image](https://user-images.githubusercontent.com/30249193/50259731-42fff700-0440-11e9-817e-54440d126448.png)
公告
![image](https://user-images.githubusercontent.com/30249193/50259739-47c4ab00-0440-11e9-8aa3-bea816d5fc0c.png)
## 期望
编辑时是什么格式在详情页就怎么展示出来

**Comment by Godkillme** [comment]
**补充**：【PC】我的钱包、我的积分页面的使用规则也是，无法换行

**Comment by maanrry** [comment]
全局评论也是如此

**Comment by maanrry** [comment]
未修复：
**补充**：【PC】我的钱包、我的积分页面的使用规则也是，无法换行

**Comment by medz** [comment]
> 未修复：
> **补充**：【PC】我的钱包、我的积分页面的使用规则也是，无法换行

迷之补充～新建 issue 是更好的选择
