### ISSUE TITLE
【pc】圈主将公开圈子或者私密免费圈子修改成私密付费圈时光标无法定位到付费输入框

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#558]
## 服务器
测试服
## 浏览器
谷歌和火狐
## 操作步骤
前提条件：公开圈子或者私密免费圈子(并且待审核列表上没有用户）
1.圈主选择自己的圈子进入圈子详情
2.点击圈子管理
3.点击付费
4.点击付费输入框
## 结果
光标无法定位到付费输入框
## 期望
光标可定位到付费输入框

**Comment by maanrry** [comment]
![image](https://user-images.githubusercontent.com/30249193/50393901-3d821400-0794-11e9-87ee-ec0a4a373f1b.png)
![image](https://user-images.githubusercontent.com/30249193/50393912-4bd03000-0794-11e9-838b-3437c40ee9d9.png)

**Comment by medz** [comment]
fixed
