### ISSUE TITLE
iOS版在iphoneX中有些二级UI和顶部距离过小，按钮被遮挡

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#559]
iOS版在iphoneX中有些二级UI和顶部距离过小，按钮被遮挡

用户优化建议：
将二级页面的顶部距离设置为统一高度。
<img width="862" alt="screen shot 2018-12-20 at 14 13 06" src="https://user-images.githubusercontent.com/33219803/50267211-73a45880-0461-11e9-8b9d-a2e7f891e19b.png">

**Comment by westudiodev** [comment]
<img width="862" alt="screen shot 2018-12-20 at 14 13 06" src="https://user-images.githubusercontent.com/33219803/50267252-920a5400-0461-11e9-8689-fe155232ec6a.png">

**Comment by Jungle68** [comment]
@westudiodev 收到，感谢反馈

**Comment by westudiodev** [comment]
2.2已经解决
