### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by ioscit** [slimkit/plus#562]
Warning: require(): open_basedir restriction in effect. File(/usr/local/src/plus/vendor/autoload.php) is not within the allowed path(s): (/usr/local/src/plus/public/:/tmp/:/proc/) in /usr/local/src/plus/public/index.php on line 33

Warning: require(/usr/local/src/plus/vendor/autoload.php): failed to open stream: Operation not permitted in /usr/local/src/plus/public/index.php on line 33

Fatal error: require(): Failed opening required '/usr/local/src/plus/public/../vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /usr/local/src/plus/public/index.php on line 33给了权限，apacheweb服务器，无法打开锕 怎么回事

**Comment by medz** [comment]
https://www.baidu.com/s?wd=apache%20Warning%3A%20require()%3A%20open_basedir%20restriction%20in%20effect.%20&rsv_spt=1&rsv_iqid=0xefa3c64000020898&issp=1&f=3&rsv_bp=1&rsv_idx=2&ie=utf-8&rqlang=cn&tn=baiduhome_pg&rsv_enter=1&inputT=1307&rsv_t=a176MHdgn3Kjy8GgX26TYj6nW2iTcEI2jByWo8v1aexM7v%2BN9jFvyT%2FcH8pqM%2FrzGi8b&oq=Warning%253A%2520require()%253A%2520open_basedir%2520restriction%2520in%2520effect.&rsv_pq=8bdeef390003320c&rsv_sug3=98&rsv_sug2=0&prefixsug=apache%2520Warning%253A%2520require()%253A%2520open_basedir%2520restriction%2520in%2520effect.%2520&rsp=4&rsv_sug4=1720

在 2018年12月20日，15:38，ioscit <notifications@github.com<mailto:notifications@github.com>> 写道：

Warning: require(): open_basedir restriction in effect.
