### ISSUE TITLE
【pc】未加入的公开圈评论时提示语不对

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#563]
## 服务器
测试服
## 操作步骤
1.用户A进入未加入的公开圈1
2.选择任意一篇帖子评论
3.输入评论内容
4.点击评论
## 结果及配图
提示语不对
![image](https://user-images.githubusercontent.com/30249193/50270734-858bf880-046d-11e9-8290-711c2ca0f9c5.png)
## 期望
![image](https://user-images.githubusercontent.com/30249193/50270801-c126c280-046d-11e9-8388-c0e1ed434702.png)

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/53629452-906ec080-3c48-11e9-9a6a-db14e17cb60c.png)
已修改！
