### ISSUE TITLE
未读消息接口返回数据缺失

### ISSUE THREAD

**Issue by mutoe** [slimkit/plus#568]
## 获取加入圈子审核信息数量缺失
`GET /api/v2/user/counts` 置顶数据只有动态评论置顶和资讯评论置顶 没有其他的置顶数据
![image](https://user-images.githubusercontent.com/9391981/50333101-28f90e00-053f-11e9-9d74-311d2cf61637.png)

**关联问题** #529 

### `/user/counts` 接口中包含 
- [ ] 帖子评论置顶
- [ ] 帖子置顶审核数量
- [ ] 圈子加入申请

或将老接口 `/api/v2/user/unread-count` 和新接口整合为一个接口

**Comment by medz** [comment]
我很好奇你们从不看历史需求吗？早说过了消息相关现在全部不修复，以后重构额开发。
