### ISSUE TITLE
【PC】我的积分-提取，该页面的按钮点击均没有反应

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#570]
PC端，我的积分-提取，“**确认**”按钮和右上角“**积分提取规则**“点击均没有反应。
<img width="769" alt="2018-12-23 21 38 38" src="https://user-images.githubusercontent.com/33575502/50384135-7b7f2980-06fb-11e9-9179-e1b1de78c06f.png">

**Comment by medz** [comment]
应该是没有加载完成页面～pc太他妈的卡了～
