### ISSUE TITLE
多端动态单图尺寸适配优化

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#571]
ios，android， H5端在高分辨率手机上单图尺寸适配不一致
ios，android， H5端在高分辨率手机上单图尺寸适配一致会比较美观
<img width="858" alt="screen shot 2018-12-24 at 23 00 17" src="https://user-images.githubusercontent.com/33219803/50402218-be123600-07cf-11e9-844b-4ef5aa06df2d.png">

**Comment by westudiodev** [comment]
<img width="858" alt="screen shot 2018-12-24 at 23 00 17" src="https://user-images.githubusercontent.com/33219803/50402239-ec901100-07cf-11e9-85f8-6e45625bb62c.png">

**Comment by medz** [comment]
你这个真不是问题，而是需求需要这样子的～
