### ISSUE TITLE
【iOS】圈子的帖子转发到动态，偶尔会显示“该内容已被删除”

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#572]
**bug描述**：圈子的帖子转发到动态，**偶尔**会显示“该内容已被删除”，而事实上，该帖子并未被删除，**多刷新几次**，又会出现。
只有圈子的帖子时不时会出现这种情况，而资讯的文章转发到动态，一直都正常。
![1](https://user-images.githubusercontent.com/33575502/50428280-30c70280-08f1-11e9-9c3c-1f4f303ca3b9.jpg)
![2](https://user-images.githubusercontent.com/33575502/50428284-37557a00-08f1-11e9-8ac7-2b6dabb5fa48.jpg)

**Comment by Jungle68** [comment]
已修复
