### ISSUE TITLE
【SPA】圈子-帖子详情页标题样式丢失

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#584]
圈子-帖子详情页，标题样式丢失，如下图：

![default](https://user-images.githubusercontent.com/33575502/50869389-bae19180-13ee-11e9-9035-30b64786eb12.jpg)

请问如果要修改SPA的样式，应该在哪个文件夹内？

**Comment by mutoe** [comment]
帖子的格式是markdown内容，如果编辑纯文本则会丢失样式，非bug

spa端使用的是vue组件，样式在相应的组件中进行修改，不再使用传统的统一样式表

帖子详情对应的位置是 `./resource/spa/src/page/group/detail/GroupPostDetail.vue`

**Comment by Godkillme** [comment]
> 
> 
> 帖子的格式是markdown内容，如果编辑纯文本则会丢失样式，非bug
> 
> spa端使用的是vue组件，样式在相应的组件中进行修改，不再使用传统的统一样式表
> 
> 帖子详情对应的位置是 `./resource/spa/src/page/group/detail/GroupPostDetail.vue`

好的，感谢！
是帖子的标题。标题如何MD格式呢，而且标题在PC端和APP端都是正常的，大一点的字号+蓝色字体，在SPA则和正文一致了。

**Comment by mutoe** [comment]
确实存在问题，感谢反馈，请等待正式版本patch更新

在此之前你可以手动添加以下内容
`GroupPostDetail.vue` L31
``` diff
   <!-- 内容 -->
      <JoLoadMore ref="loadmore" @onRefresh="fetchFeed">
        <main class="m-flex-shrink1 m-flex-grow1 m-art m-main">
          <div class="m-art-body">
            <h2 v-if="title" class="post-title">{{ title }}</h2>
+           <p class="description">来自 <span>{{ group.name }}</span></p>
```

`GroupPostDetail.vue` L673
``` diff
<style lang="less" scoped>
- .post-title {
-   font-size: 32px;
- }
+ .post-title {
+   margin-top: 20px;
+   font-size: 1.5em;
+ }
+ 
+ .description {
+   margin-top: 20px;
+   color: #ccc;
+   font-size: 28px;
+ 
+   > span {
+     color: @primary;
+   }
+ }
</style>
```
