### ISSUE TITLE
spa登录成功，但是访问其他接口401

### ISSUE THREAD

**Issue by bm1987215** [slimkit/plus#585]
将spa就部署在项目下面，能够登录成功并且返回了token，但是用这个token调用数据始终是401
![1](https://user-images.githubusercontent.com/4496232/50871012-41996d00-13f5-11e9-86e8-f3093bd7969d.png)
![2](https://user-images.githubusercontent.com/4496232/50871022-45c58a80-13f5-11e9-8c54-7434c86a9f56.png)
![3](https://user-images.githubusercontent.com/4496232/50871026-478f4e00-13f5-11e9-983e-e2859adf72e8.png)

**Comment by mutoe** [comment]
未能复现，需要自行排查（如换个环境、清空缓存、postman调试等

**Comment by bm1987215** [comment]
缓存和postman都试过了。
下面是的我的php环境
System | Windows NT DESKTOP-D55K04F 10.0 build 17134 (Windows 10) i586
-- | --
Build Date | Dec 5 2018 07:16:00
Compiler | MSVC15 (Visual C++ 2017)
Architecture | x86
Configure Command | cscript /nologo configure.js "--enable-snapshot-build" "--enable-debug-pack" "--with-pdo-oci=c:\php-snap-build\deps_aux\oracle\x86\instantclient_12_1\sdk,shared" "--with-oci8-12c=c:\php-snap-build\deps_aux\oracle\x86\instantclient_12_1\sdk,shared" "--enable-object-out-dir=../obj/" "--enable-com-dotnet=shared" "--without-analyzer" "--with-pgo"
Server API | CGI/FastCGI
Virtual Directory Support | enabled
Configuration File (php.ini) Path | C:\WINDOWS
Loaded Configuration File | D:\xampp\php\php.ini
Scan this dir for additional .ini files | (none)
Additional .ini files parsed | (none)
PHP API | 20170718
PHP Extension | 20170718
Zend Extension | 320170718
Zend Extension Build | API320170718,TS,VC15
PHP Extension Build | API20170718,TS,VC15
Debug Build | no
Thread Safety | enabled
Zend Signal Handling | disabled
Zend Memory Manager | enabled
Zend Multibyte Support | provided by mbstring
IPv6 Support | enabled
DTrace Support | disabled
Registered PHP Streams | php, file, glob, data, http, ftp, zip, compress.zlib, compress.bzip2, https, ftps, phar
Registered Stream Socket Transports | tcp, udp, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters | convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, zlib.*, bzip2.*

**Comment by mutoe** [comment]
@medz 请求协助😂

**Comment by medz** [comment]
```bash
php artisan app:key
```
然后重新登录
