### ISSUE TITLE
热门话题接口报错

### ISSUE THREAD

**Issue by mutoe** [slimkit/plus#586]
**Describe the bug**
<img width="597" alt="default" src="https://user-images.githubusercontent.com/9391981/50873538-6f81b000-13fb-11e9-984b-7a175ece364a.png">

**To Reproduce**
1. request GET `http://test-plus.zhibocloud.cn/api/v2/feed/topics?only=hot`

**Additional context**
branch: master

**Comment by mutoe** [comment]
@medz 似乎漏改了一处 😂
https://github.com/slimkit/plus/blob/d47e3dd09f1faa5d2055bcc10ec1ce0ce9449987/app/API2/Controllers/Feed/Topic.php#L85

**Comment by medz** [comment]
收到

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2019年1月9日，17:40，mutoe <notifications@github.com<mailto:notifications@github.com>> 写道：


@medz<https://github.com/medz> 似乎漏改了一处 😂
https://github.com/slimkit/plus/blob/d47e3dd09f1faa5d2055bcc10ec1ce0ce9449987/app/API2/Controllers/Feed/Topic.php#L85
