### ISSUE TITLE
【SPA】问题详情页底部缺少功能

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#587]
## 服务器
测试服
## 描述
问题详情页底部缺少评论、分享、编辑（发布者自己的才有）、更多等入口
## 配图
![image](https://user-images.githubusercontent.com/30249193/50879549-3f93d600-1416-11e9-8f7b-b7012bf2ce3f.png)
## 移动端
![image](https://user-images.githubusercontent.com/30249193/50879619-79fd7300-1416-11e9-83a4-9a1162ce5d91.png)

**Comment by mutoe** [comment]
- [ ] 评论

- [ ] 编辑

- [ ] 举报

**Comment by Jungle68** [comment]
不需要编辑

**Comment by LMTcancan** [comment]
h5只有一个评论按钮 放到右上角更多里面了
