### ISSUE TITLE
用户注册的用户名存在漏洞，用户名不存在

### ISSUE THREAD

**Issue by Jungle68** [slimkit/plus#589]
**Describe the bug**
服务器信息：https://tsplus.zhibocloud.cn

错误用户
![image](https://user-images.githubusercontent.com/7939686/50884846-03b53c80-1427-11e9-8437-275999b4ed1c.png)

注册来源不清楚。已将空用户名修改为”非法用户“

**Comment by medz** [comment]
这不是 Bug，从 2.1 版本开始允许用户不设置用户名，但是邮箱或者手机号码必须存在一项！
