### ISSUE TITLE
【SPA】提问者进入他人的回答详情页没有采纳入口

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#591]
## 服务器
测试服
## 描述
用户A提问，用户B添加回答，用户A进入用户B的回答详情页没有采纳入口
## 期望
问题没有采纳答案时，进入他人的回答详情页面有采纳入口，问题已经有采纳回答之后进入回答详情无采纳入口

**Comment by LMTcancan** [comment]
问题已有采纳回答之后，进入另一个回答详情仍然有“采纳答案”按钮
期望：没有“采纳答案”按钮

**Comment by maanrry** [comment]
现在没有采纳回答是进入任意一个回答详情都没有采纳按钮
