### ISSUE TITLE
【SPA】问题详情页点击未设置悬赏未进入公开悬赏页面

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#598]
## 服务器
测试服
## 描述
用户自己发布的未设置悬赏的问题，进入问题详情页后点击“未设置悬赏”，没有进入公开悬赏页面
## 期望
点击“未设置悬赏”进入公开悬赏页面
![image](https://user-images.githubusercontent.com/30249193/51095603-e7cbe500-17f0-11e9-83da-30ccf8a5c1b6.png)

**Comment by LMTcancan** [comment]
@maanrry 已修复
