### ISSUE TITLE
【SPA】圈主进入圈子详情页侧边栏权限不对

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#599]
## 服务器
测试服
## 描述
圈主进入圈子详情页侧边栏权限不对
## 结果配图
![image](https://user-images.githubusercontent.com/30249193/51095904-16e35600-17f3-11e9-90d2-3cbaae2049aa.png)
## 期望
![image](https://user-images.githubusercontent.com/30249193/51095907-1e0a6400-17f3-11e9-952c-1a7b28751952.png)

**Comment by Jungle68** [comment]
不做处理
