### ISSUE TITLE
【SPA】我的投稿-被驳回的文章仍然取的是投稿中的文章

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#603]
## 服务器
测试
## 描述
1.我的投稿-被驳回的文章仍然取的是投稿中的文章
2.我的投稿-投稿中，点击文章之后仍然进去文章详情还有其他操作以及显示了相关文章
## 期望
1.我的投稿-被驳回列表：取被后台驳回的文章
2.处于投稿中的文章，点击之后进入文章详情，没有相关文章也没有其他任何操作；只是文章内容的展示而已

**Comment by LMTcancan** [comment]
点击我的投稿-被驳回的文章，进入文章详情展示页面
期望：进入文章编辑页面

**Comment by mutoe** [comment]
> 点击我的投稿-被驳回的文章，进入文章详情展示页面
> 期望：进入文章编辑页面

@LMTcancan H5 没有编辑资讯的功能

**Comment by westudiodev** [comment]
> 点击我的投稿-被驳回的文章，进入文章详情展示页面
> 期望：进入文章编辑页面

H5最好越简单越好。最好就是为app导流。最好只是展示。

- 非官方产品总监（QQ：770343868）

**Comment by maanrry** [comment]
已修复
