### ISSUE TITLE
【SPA】发现-排行榜-用户：显示错误

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#606]
## 服务器
测试服
## 描述
列表显示不统一
## 配图
![image](https://user-images.githubusercontent.com/30249193/51302731-2e7a4300-1a6e-11e9-9d84-ea781df32a43.png)
## 期望
![image](https://user-images.githubusercontent.com/30249193/51302756-405be600-1a6e-11e9-8dff-748b62402986.png)

**Comment by LMTcancan** [comment]
最下面两个排行榜title应该分别是“社区专家排行榜”和“问答大人排行榜”。现在显示不对

**Comment by maanrry** [comment]
未修复
![image](https://user-images.githubusercontent.com/30249193/54004057-3e212880-418f-11e9-8757-78aca8e893de.png)
