### ISSUE TITLE
【SPA】用户在SPA端设置定位后可能在其他端无法读取的问题

### ISSUE THREAD

**Issue by mutoe** [slimkit/plus#608]
**To Reproduce**
1. 在SPA端设置个人用户位置为某地址
2. 保存后用户的user.location字段只有“成都市”或“上海市”一段内容
3. 在IOS端无法读取已保存字段

**Expected behavior**
在SPA端保存为“四川省 成都市”或“中国 上海市”

**Comment by westudiodev** [comment]
mutoe

你好，我看你在github上提了很多关于ts+的issue，请问您是ts+团队开发人员吗？有几个技术问题想求助下。

主要是关于app反应速度为何会明显慢于vue版

**Comment by mutoe** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好，我是SPA端开发人员。这个问题我猜测和技术选型与接口返回的数据结构有关，某些页面需要很多来自不同接口数据，这导致了在请求某个页面耗时较长的问题。至于为什么vue会比app快，举个例子，访问动态详情时，会首先发起一个请求资讯内容的核心接口，等接口返回数据后，先展示资讯内容，再开始并发请求其他接口（如相关资讯、打赏、点赞、评论等信息），拿到数据后再注入到页面中，这似乎会比并发多个请求要快。（你可以使用chrome 打开开发者模式切换一个较慢的网络速度，然后观察资讯详情页的数据流以及页面数据的注入过程）
    其他端不知道是怎么处理的，也有可能是其他原因，感谢你的关注。
    
    
    

    

    

    在2019年01月21日 16:37，westudiodev<notifications@github.com> 写道： 


mutoe

你好，我看你在github上提了很多关于ts+的issue，请问您是ts+团队开发人员吗？有几个技术问题想求助下。

主要是关于app反应速度为何会明显慢于vue版

**Comment by medz** [comment]
很简单，spa 是异步，app 是同步

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2019年1月21日，18:02，mutoe <notifications@github.com<mailto:notifications@github.com>> 写道：







font{
line-height: 1.6;
}
ul,ol{
padding-left: 20px;
list-style-position: inside;
}



你好，我是SPA端开发人员。这个问题我猜测和技术选型与接口返回的数据结构有关，某些页面需要很多来自不同接口数据，这导致了在请求某个页面耗时较长的问题。至于为什么vue会比app快，举个例子，访问动态详情时，会首先发起一个请求资讯内容的核心接口，等接口返回数据后，先展示资讯内容，再开始并发请求其他接口（如相关资讯、打赏、点赞、评论等信息），拿到数据后再注入到页面中，这似乎会比并发多个请求要快。（你可以使用chrome 打开开发者模式切换一个较慢的网络速度，然后观察资讯详情页的数据流以及页面数据的注入过程）
其他端不知道是怎么处理的，也有可能是其他原因，感谢你的关注。








在2019年01月21日 16:37，westudiodev<notifications@github.com<mailto:notifications@github.com>> 写道：


mutoe

你好，我看你在github上提了很多关于ts+的issue，请问您是ts+团队开发人员吗？有几个技术问题想求助下。

主要是关于app反应速度为何会明显慢于vue版

**Comment by LMTcancan** [comment]
已修复
