### ISSUE TITLE
用户需求建议- 【App】短视频交互优化

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#612]
1. 优化全屏播放UI
2. 弹出评论层优化
3. 上下滑动，切换视频

<img width="862" alt="screen shot 2019-01-24 at 18 32 19" src="https://user-images.githubusercontent.com/33219803/51672461-7ec14a00-2006-11e9-9fe4-e16bd4f052be.png">

---
悬赏奖金最高5千元

**Comment by medz** [comment]
ts+ 暂无这方面优化考虑
