### ISSUE TITLE
用户需求建议：【App】取消动态详情页

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#614]
* 点击详情页不跳转，而是直接在当前页展开并显示收起按钮
* 点击评论弹出评论层
* 点击打赏弹出打赏层
<img width="858" alt="screen shot 2019-01-24 at 19 04 23" src="https://user-images.githubusercontent.com/33219803/51674159-e2e60d00-200a-11e9-90dc-b96b518e5a12.png">
---
任务悬赏3千元起

**Comment by medz** [comment]
暂无这方面考虑～
