### ISSUE TITLE
用户需求建议- 增加地理位置相关功能

### ISSUE THREAD

**Issue by hrhy999** [slimkit/plus#615]
在用户主页增加用户位置的显示，增大附近的人的范围，不只限于50KM，可用户自定义
动态增加发布动态时的位置信息并显示，可按位置查找附近发表的动态，附近的范围，可用户自定义，不只限于50KM以内

**Comment by boxshadow** [comment]
@hrhy999 高德限制, 最多只能计算50KM范围内的距离数据
