### ISSUE TITLE
后台生成的图像缩略图太多，太浪费空间！！

### ISSUE THREAD

**Issue by hrhy999** [slimkit/plus#623]
**Is your feature request related to a problem? Please describe.**
发布一张动态图片后，对这一张图片，后台生成了大量的缩略图，占用了大量空间。目前发现，一张图片，缩略图数量多的达25张，并且这些图中，有3张的分辨率和原图一样的。
官方技术人员解释说，为了达到最好的界面显示效果，对每一种分辨率的移动设备，都分别生成4张缩略图。

**Describe the solution you'd like**
建议对缩略图进行合并，相近分辨率的缩略图，只生成一个即可，每张图片的缩略图总数控制在4张内。界面上的显示效果，可通过客户端代码来处理。

**Describe alternatives you've considered**

**Additional context**

**Comment by medz** [comment]
那我问你一个问题，为什么你不用云存储？非要用 Local ？Local 就两种方案，一种是空间环速度（同时降低 CPU 使用），一种是计算性能+时间换空间。很明显，在 local 驱动上我们选择了空间换时间和计算性能的选择，原因就是储存相对 CPU 成本会更低。不生产缩略图代表每个缩略请求进来都要进行处理。而你所说的那么多缩略图乃需求所致，程序会根据当前设备尺寸计算显示区域最佳像素，，你所说的合并也是不现实的，你只会看分辨率么？图片质量、高斯模糊等参数都被你忽略了。你所谓的分辨率其实是画布尺寸。在 local 上面质量相差 10% 的图片肉眼看起来差别很细微，但是在 ts+ 的付费图片上差别就有了。

## 建议

那么在乎储存空间，可以切换为七牛或者 OSS 这样文件只有一份。

## Tips

在现在的设备价格来看，一块 560GB 的云存储盘仅需几百块一年，其中可以储存的量可想而知，如果采用性能换空间的方法，CPU 生层性能升级价格每年至少几千块。所以你仔细参考服务器各项硬件配置价格后再来看待这个问题吧。最节省成本的方法是放到 OSS 或者七牛上去。你用 local 数据在服务器上始终会时时刻刻消耗。只是相对云存储消耗少一点而已。

**Comment by medz** [comment]
其次你说的客户端代码处理效果，你不考虑网络情况？

**Comment by westudiodev** [comment]
> **Is your feature request related to a problem? Please describe.**
> 发布一张动态图片后，对这一张图片，后台生成了大量的缩略图，占用了大量空间。目前发现，一张图片，缩略图数量多的达25张，并且这些图中，有3张的分辨率和原图一样的。
> 官方技术人员解释说，为了达到最好的界面显示效果，对每一种分辨率的移动设备，都分别生成4张缩略图。
> 
> **Describe the solution you'd like**
> 建议对缩略图进行合并，相近分辨率的缩略图，只生成一个即可，每张图片的缩略图总数控制在4张内。界面上的显示效果，可通过客户端代码来处理。
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

我写了一个文档或许对你有帮助。你加QQ群：516682889
