### ISSUE TITLE
收到的评论-新接口问题

### ISSUE THREAD

**Issue by icepring** [slimkit/plus#625]
- [x] 缺少字段 reply_user：该条评论回复某个用户
![image](https://user-images.githubusercontent.com/11835710/53462354-7ed9bd00-3a7e-11e9-8e43-5554ef263822.png)

- [x] 需要 批量获取专辑信息&批量获取单曲信息接口支持 
![image](https://user-images.githubusercontent.com/11835710/53462080-8187e280-3a7d-11e9-8ba9-6de49f9d3886.png)

- [x] 单曲评论失败
![image](https://user-images.githubusercontent.com/11835710/53462130-b85df880-3a7d-11e9-88cb-0e7a2ac05ec8.png)

**Comment by westudiodev** [comment]
> * [ ]  缺少字段 reply_user：该条评论回复某个用户
>   ![image](https://user-images.githubusercontent.com/11835710/53462354-7ed9bd00-3a7e-11e9-8e43-5554ef263822.png)
> * [ ]  需要 批量获取专辑信息&批量获取单曲信息接口支持
>   ![image](https://user-images.githubusercontent.com/11835710/53462080-8187e280-3a7d-11e9-8ba9-6de49f9d3886.png)
> * [ ]  单曲评论失败
>   ![image](https://user-images.githubusercontent.com/11835710/53462130-b85df880-3a7d-11e9-88cb-0e7a2ac05ec8.png)

你好，我在app上评论单曲，但是并没有异常。

**Comment by westudiodev** [comment]
> * [ ]  缺少字段 reply_user：该条评论回复某个用户
>   ![image](https://user-images.githubusercontent.com/11835710/53462354-7ed9bd00-3a7e-11e9-8e43-5554ef263822.png)
> * [ ]  需要 批量获取专辑信息&批量获取单曲信息接口支持
>   ![image](https://user-images.githubusercontent.com/11835710/53462080-8187e280-3a7d-11e9-8ba9-6de49f9d3886.png)
> * [ ]  单曲评论失败
>   ![image](https://user-images.githubusercontent.com/11835710/53462130-b85df880-3a7d-11e9-88cb-0e7a2ac05ec8.png)

呵呵，你也在关注kotlin和weex吗？来我们这个weex大前端群看看有你想要的 qq群：516682889

**Comment by westudiodev** [comment]
关于ts+的FM音频模块我们需要优化成类似得到App音频的形式。希望沟通下需求：QQ 770343868

**Comment by medz** [comment]
> 关于ts+的FM音频模块我们需要优化成类似得到App音频的形式。希望沟通下需求：QQ 770343868

@westudiodev 通过官网客服可联系得到，如果是授权客户直接在授权小组可以联系得到。

**Comment by westudiodev** [comment]
> > 关于ts+的FM音频模块我们需要优化成类似得到App音频的形式。希望沟通下需求：QQ 770343868
> 
> @westudiodev 通过官网客服可联系得到，如果是授权客户直接在授权小组可以联系得到。

ok，加了你们QQ，通过下啊。
