### ISSUE TITLE
【PC】全局的详情页评论之后没有评论成功的提示也没有自动刷新页面

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#629]
## 服务器
正式服
## 描述
全局的详情页评论之后没有评论成功的提示也没有自动刷新页面
如：在动态列表上选择任意一条动态进入帖子详情，输入评论内容点击评论，评论成功之后没有提示也没有自动刷新页面
详情页有：动态详情、帖子详情、回答详情、问题详情
## 配图
![image](https://user-images.githubusercontent.com/30249193/53614966-ae233200-3c16-11e9-871c-f07a18efc876.png)

**Comment by medz** [comment]
fixed.
