### ISSUE TITLE
【PC】圈子管理-圈子成员-待审核，圈主点击通过报错了

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#630]
## 服务器
测试服
##描述
圈子管理-圈子成员-待审核，圈主点击通过报错了
账号：屌炸天  123456  圈子：猫
## 配图
![image](https://user-images.githubusercontent.com/30249193/53615121-74066000-3c17-11e9-84c7-11c51c0f9734.png)
## 期望
可操作成功

**Comment by medz** [comment]
表明服务器。。。。

**Comment by medz** [comment]
排查完毕，环境错误导致！并不是程序问题
