### ISSUE TITLE
【审核】- 同意加圈申请

### ISSUE THREAD

**Issue by icepring** [slimkit/plus#631]
- 接口 ：http://test-plus.zhibocloud.cn/api/v2/plus-group/currency-groups/9/members/117/audit
![image](https://user-images.githubusercontent.com/11835710/53621107-5d203780-3c30-11e9-9a3d-e3142ceb9839.png)

**Comment by medz** [comment]
测试服环境出现了问题所致～暂时无法解决，并非程序 bug～
