### ISSUE TITLE
【PC】进入“bug反馈”圈子报错

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#632]
## 服务器
正式服

## 浏览器
Safari、Google Chrome

## 链接
https://tsplus.zhibocloud.cn/groups/12

## 配图
![060ebaee-0b03-425c-89b0-30e3e63e45ed](https://user-images.githubusercontent.com/25689097/53624085-f6a01700-3c39-11e9-9e8a-6cba335789be.png)

**Comment by medz** [comment]
正式服环境出了问题，这个不是程序  bug
