### ISSUE TITLE
【PC】作为圈主，设置地址之后，地址显示不全

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#633]
## 服务器
正式服

## 浏览器
Safari

## 操作
1. 进入自己的圈子，选择“圈子管理”
2. 点击“圈子位置” 
3. 输入关键字
4. 点击前面显示搜索图标的内容 
5. 点击某一个位置
6. 点击“确定”

![e2f33bea-bf85-4270-82e5-263106bd94d8](https://user-images.githubusercontent.com/25689097/53624904-a70f1a80-3c3c-11e9-89de-0163a0034d9a.png)
![703c1589-0398-4a37-be24-1d529b935df1](https://user-images.githubusercontent.com/25689097/53624907-a8d8de00-3c3c-11e9-9468-280736913130.png)

## 结果
返回上一页，地址显示缺少省、市级区域
![29d0389d-638c-4371-8da6-3daaf59bea62](https://user-images.githubusercontent.com/25689097/53624945-bc844480-3c3c-11e9-8b19-153d515bd474.png)

**Comment by maanrry** [comment]
已修复
