### ISSUE TITLE
【PC-bug】发布动态上传图片报错

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#637]
## 服务器
正式服

## 浏览器
Safari

## 配图
<img width="452" alt="image" src="https://user-images.githubusercontent.com/25689097/53707054-23d20c80-3e68-11e9-8440-bb2a89d2ad38.png">

**Comment by westudiodev** [comment]
Android图片上传也报错

**Comment by mutoe** [comment]
未复现
