### ISSUE TITLE
【SPA-bug】动态列表GIF图没有自动播放

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#641]
## 服务器
测试服

## 描述
动态列表GIF图没有自动播放
点击查看大图后才开始播放

## 预期
<img width="635" alt="image" src="https://user-images.githubusercontent.com/25689097/53717006-ca7ed300-3e91-11e9-9491-94a3cf4af3a5.png">

**Comment by maanrry** [comment]
已修复
