### ISSUE TITLE
【后台-动态管理】查看有图片的动态，图片显示与实际不符

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#645]
## 服务器
正式服

## 描述
查看有图片的动态，图片显示与实际不符

## 配图
![e0c4ae02cf5de1b2f839cd16393312cb](https://user-images.githubusercontent.com/25689097/53722676-0e2d0900-3ea1-11e9-96d7-15fde80217b4.png)
![e0e7e333896bffe3b50e3008cfc42b9f](https://user-images.githubusercontent.com/25689097/53722679-0ec59f80-3ea1-11e9-8ed9-e69ac9d55ffe.png)

**Comment by mutoe** [comment]
重复问题 https://github.com/slimkit/plus/issues/624
