### ISSUE TITLE
【SPA-bug】通知-审核通知无法切换到其他审核页面

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#650]
## 服务器
测试服

## 描述
通知-审核通知无法切换到其他审核页面

## 配图
<img width="286" alt="image" src="https://user-images.githubusercontent.com/25689097/53777514-98727d00-3f34-11e9-85ee-c99dcd100e97.png">

## 预期
<img width="234" alt="image" src="https://user-images.githubusercontent.com/25689097/53777456-67924800-3f34-11e9-8da1-dedba2254569.png">

**Comment by LMTcancan** [comment]
未修复

**Comment by maanrry** [comment]
Safari 没有下拉弹窗
