### ISSUE TITLE
【PC-bug】收到的点赞、评论的视频动态没有显示封面图

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#653]
## 服务器
测试服

## 描述
1. 收到的评论内容会显示在系统消息下方
2. 视频动态被评论/点赞后，收到的评论/点赞消息列表没有显示图片

## 配图
![c9615bf3-8a0b-4f36-8963-fab0d662d8b8](https://user-images.githubusercontent.com/25689097/53783803-1c852e80-3f4e-11e9-9b1e-b623098a31e5.png)

<img width="286" alt="image" src="https://user-images.githubusercontent.com/25689097/53783798-18f1a780-3f4e-11e9-9b78-2a0f265b435c.png">

<img width="283" alt="image" src="https://user-images.githubusercontent.com/25689097/53783944-91f0ff00-3f4e-11e9-8d04-c284b40e2436.png">

## 预期
1. 评论不显示在系统消息下
2. 显示视频封面图
<img width="272" alt="image" src="https://user-images.githubusercontent.com/25689097/53784137-42f79980-3f4f-11e9-959b-33a4e33bc79c.png">

**Comment by LMTcancan** [comment]
PC端收到的视频动态点赞、评论也没有显示封面图

**Comment by maanrry** [comment]
H5已修复，pc端没有修复
