### ISSUE TITLE
【SPA-bug】没有消息数据的账号有多处显示不对

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#655]
## 服务器
测试服

## 描述
1. 没有数据时进入消息页面空白，刷新之后才有内容
2. title显示为“消息”，应该是“通知”
3. 没有数据是时间显示为“NAN”
4. 系统消息、收到的评论、收到的赞缺省文字不对

账号：18408298223      123456

## 配图
![11edcd1f-300d-4ecc-bb86-b8cc0b1563bc](https://user-images.githubusercontent.com/25689097/53851527-ef8e5580-3ff9-11e9-8df3-ed2248653c88.png)
<img width="285" alt="image" src="https://user-images.githubusercontent.com/25689097/53851597-1f3d5d80-3ffa-11e9-88b4-d16f70c1447a.png">

## 预期
<img width="235" alt="image" src="https://user-images.githubusercontent.com/25689097/53851683-67f51680-3ffa-11e9-9096-96b0e93bda1d.png">

**Comment by LMTcancan** [comment]
1. 审核通知的占位文字不对
2. 从其他页面进入通知页面还是显示空白，刷新后才显示正确内容
<img width="293" alt="image" src="https://user-images.githubusercontent.com/25689097/53939768-0793d100-40ef-11e9-89a4-bf202a03e48c.png">

**Comment by maanrry** [comment]
未修复，消息列表上显示的时间格式仍然不对
![image](https://user-images.githubusercontent.com/30249193/54003679-f352e100-418d-11e9-9a55-d7b87d55ed18.png)

**Comment by LMTcancan** [comment]
没有审核通知时占位文字不对。期望：暂无未审核的申请
<img width="280" alt="image" src="https://user-images.githubusercontent.com/25689097/54095849-30b0ac00-43e4-11e9-970a-e1fc4777105b.png">

**Comment by LMTcancan** [comment]
未修复

**Comment by LMTcancan** [comment]
已修复
