### ISSUE TITLE
【SPA-bug】全局，使用默认头像的用户修改性别后，头像没有根据性别进行改变

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#658]
## 服务器
测试服

## 描述
使用默认头像的用户修改性别后，头像没有根据性别进行改变

## 配图
<img width="287" alt="image" src="https://user-images.githubusercontent.com/25689097/53854358-2a958680-4004-11e9-95e5-62b277a10d9f.png">

## 预期
<img width="228" alt="image" src="https://user-images.githubusercontent.com/25689097/53854304-e86c4500-4003-11e9-927a-9cb9a8d07656.png">

**Comment by maanrry** [comment]
已修复
