### ISSUE TITLE
【PC-bug】动态列表所有图片都有GIF标识

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#660]
## 服务器
测试服

## 浏览器
Safari

## 描述
动态列表所有图片都有GIF标识，包括长图和普通静态图

## 配图
<img width="489" alt="image" src="https://user-images.githubusercontent.com/25689097/53925555-54f64b00-40bb-11e9-94f8-347df19ae0a2.png">

<img width="502" alt="image" src="https://user-images.githubusercontent.com/25689097/53925537-46a82f00-40bb-11e9-9e6c-0a461d893aca.png">

## 预期
只有GIF图片才显示GIF图标，长图显示长图图片，普通图片没有图标

**Comment by LMTcancan** [comment]
长图缺少标识

**Comment by maanrry** [comment]
已修复
