### ISSUE TITLE
【SPA、PC-bug】系统消息点击用户名仍然进入圈子详情

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#669]
## 服务器
测试服
### 描述
系统消息点击用户名仍然进入圈子详情
### 期望
![image](https://user-images.githubusercontent.com/30249193/54004596-13d06a80-4191-11e9-9b69-62106a72d69c.png)

**Comment by mutoe** [comment]
没有此类消息，只有审核消息 现在会跳到审核页面
