### ISSUE TITLE
圈子加入审核时报错

### ISSUE THREAD

**Issue by mutoe** [slimkit/plus#670]
测试服
PATCH `http://test-plus.zhibocloud.cn/api/v2/plus-group/currency-groups/7/members/142/audit`
token

    Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vdGVzdC1wbHVzLnpoaWJvY2xvdWQuY24vYXBpL3YyL2F1dGgvbG9naW4iLCJpYXQiOjE1NTIwMTUwNzUsImV4cCI6MTU1MzMxMTA3NSwibmJmIjoxNTUyMDE1MDc1LCJqdGkiOiJNQ2NBWU1QanAyRDFOUnhwIiwic3ViIjoxMywicHJ2IjoiNDhlNDUzODMxY2ViYTVlNTdhNDc1ZTY4NjQ5Y2ZkZWU2ZTk3ZDhkMiJ9.WFeHsnsMmJ74ZihZfBSEOZdNiE-3HQ7ExNq7jbhivCc

### response
status 500
``` json
{"message":["Use of undefined constant e - assumed 'e' (this will throw an Error in a future version of PHP)"]}
```

**Comment by medz** [comment]
无法修复～因为根本排查不出报错的地方
