### ISSUE TITLE
系统消息接口返回的打赏帖子类型字段名为数字

### ISSUE THREAD

**Issue by mutoe** [slimkit/plus#682]
**Describe the bug**
GET `http://test-plus.zhibocloud.cn/api/v2/user/notifications?type=system`

**token**

     Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vdGVzdC1wbHVzLnpoaWJvY2xvdWQuY24vYXBpL3YyL2F1dGgvbG9naW4iLCJpYXQiOjE1NTIwMjk3MTgsImV4cCI6MTU1MzMyNTcxOCwibmJmIjoxNTUyMDI5NzE4LCJqdGkiOiI3WGRiRWVFOFBxVEhIMGFuIiwic3ViIjozLCJwcnYiOiI0OGU0NTM4MzFjZWJhNWU1N2E0NzVlNjg2NDljZmRlZTZlOTdkOGQyIn0.SZVYuFRVEJpUd1P0SKOPOwPGCyOCz8zb-VeOv9Gatis

![图片](https://user-images.githubusercontent.com/9391981/54108239-5fe01100-4416-11e9-9335-10e4f3b6016c.png)

期望改为与列表中其他数据结构一致

**Comment by medz** [comment]
旧数据无法更改，新产生的数据不会再出现
