### ISSUE TITLE
【PC-bug】动态详情，评论模块有三处显示问题

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#686]
## 服务器
测试服

## 浏览器
Safari

## 描述
1. 评论内容前多余空白部分
2. 他人评论“回复”按钮显示错误
3. 回复他人评论后，评论内容显示错误

## 配图
![DB5A110E-3DE4-44A7-A271-100F55FE2749](https://user-images.githubusercontent.com/25689097/54179169-f83bcb80-44d2-11e9-9e65-60e250621903.png)

## 预期
1. 评论内容和昵称对齐
2. 按钮显示为“回复”
3. 评论内容显示为：  “回复” + 用户昵称： 回复内容

**Comment by maanrry** [comment]
在详情页回复他人之后没有刷新页面时仍然显示成一条新的评论
![image](https://user-images.githubusercontent.com/30249193/54731870-aa5a4e00-4bcb-11e9-80a5-45e220318cc3.png)
刷新之后：
![image](https://user-images.githubusercontent.com/30249193/54731876-b0502f00-4bcb-11e9-8ff8-91fbba4a4c19.png)

**Comment by maanrry** [comment]
@mutoe
