### ISSUE TITLE
【PC-bug】动态列表@某人的动态用户名没有高亮

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#687]
## 服务器
测试服

## 浏览器
Safari 、Google

## 描述
1. @某人的动态用户名没有高亮
2. @某人后输入很多文字内容，发布成功后，“查看更多”按钮没有高亮
3. 评论动态时手动输入@，操作向下按钮，第二个好友昵称没有高亮（存在多个好友）

## 配图
![889A7B57-E744-4B31-9B7E-E082BD8ACAB1](https://user-images.githubusercontent.com/25689097/54181225-cc234900-44d8-11e9-990b-7142719bae70.png)
<img width="264" alt="image" src="https://user-images.githubusercontent.com/25689097/54181238-d8a7a180-44d8-11e9-9689-01945dc4dd83.png">

**Comment by maanrry** [comment]
@mutoe 第二点和第三点没有修复

**Comment by maanrry** [comment]
@mutoe  第二点没有修复
2.@某人后输入很多文字内容，发布成功后，“查看更多”按钮没有高亮
