### ISSUE TITLE
【PC-bug】认证管理，认证信息中认证状态和被驳回理由显示错误

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#688]
## 服务器
测试服

## 浏览器
Safari

## 描述
1. 所有认证状态都显示错误（待审核、已驳回、已认证）
2. 被驳回的驳回理由显示错误
账号：13808069927     123456

## 配图
<img width="651" alt="image" src="https://user-images.githubusercontent.com/25689097/54181973-29b89500-44db-11e9-8c7b-41926baf277e.png">

**Comment by LMTcancan** [comment]
我的钱包-提现记录
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/25689097/54182427-7650a000-44dc-11e9-80cc-064b24479c04.png">

**Comment by LMTcancan** [comment]
我的积分-积分充值
<img width="362" alt="image" src="https://user-images.githubusercontent.com/25689097/54182531-ba43a500-44dc-11e9-83a0-f4df9cf9316e.png">

**Comment by LMTcancan** [comment]
圈子-更多圈子成员
<img width="385" alt="image" src="https://user-images.githubusercontent.com/25689097/54185254-86b84900-44e3-11e9-9112-9fb639aa465e.png">

**Comment by maanrry** [comment]
@mutoe 未修复：
1.
![image](https://user-images.githubusercontent.com/30249193/54732111-f5289580-4bcc-11e9-8368-932642260c2a.png)
