### ISSUE TITLE
【ADMIN-bug】举报帖子报错

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#689]
## 服务器
测试服
## 描述
选择任意一个圈子进入帖子详情，选择除了自己的帖子点击举报，输入举报理由，点击举报，报错
## 配图
![image](https://user-images.githubusercontent.com/30249193/54182410-68028400-44dc-11e9-8cc2-a991f90dd9c1.png)
## 期望
可举报成功

**Comment by mutoe** [comment]
重复问题 #677

**Comment by medz** [comment]
@mutoe 提供下调用的 API

**Comment by mutoe** [comment]
> @mutoe 提供下调用的 API

POST `http://test-plus.zhibocloud.cn/api/v2/plus-group/reports/posts/48`
