### ISSUE TITLE
【PC-优化】搜索历史英文内容被截掉下半部分

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#690]
## 服务器
测试服

## 浏览器
Safari

## 配图
<img width="257" alt="image" src="https://user-images.githubusercontent.com/25689097/54184386-84ed8600-44e1-11e9-80d3-e62acba5aa5f.png">

**Comment by maanrry** [comment]
输入内容之后显示搜索列表有问题
![image](https://user-images.githubusercontent.com/30249193/54731481-623a2c00-4bc9-11e9-93f5-93a405ec6c18.png)

**Comment by maanrry** [comment]
@mutoe 需要再看看
