### ISSUE TITLE
【ADMIN-bug】进入发现-找人-附近报错

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#692]
## 服务器
测试服

## 描述
进入发现-找人-附近报错

http://test-plus.zhibocloud.cn/api/v2/around-amap?latitude=30.559467&limit=15&longitude=104.033722&page=1&radius=3000

## 配图
<img width="238" alt="image" src="https://user-images.githubusercontent.com/25689097/54250233-e7945f80-457d-11e9-8512-ffa278a0f874.png">

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/25689097/54250306-3e9a3480-457e-11e9-85d7-1ef3b90a5b60.png">

**Comment by boxshadow** [comment]
后台「附近的人」配置的高德地图错误
