### ISSUE TITLE
【ADMIN-BUG】后台注册开启强制完善资料之后，在注册时仍然可以跳转选择标签

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#701]
## 服务器
测试服
## 描述
1.后台进入用户中心-注册设置-完善资料选择：注册时强制完善
2.前端注册走到选择标签页面
3.点击跳过
## 结果
仍然可以跳过选择标签
## 期望
后台选择注册时强制完善资料时，注册走到选择标签页面就应该必选选择标签，不能直接点击跳过

**Comment by boxshadow** [comment]
这个是移动端需要控制的
