### ISSUE TITLE
【PC】圈子成员页面显示不正常

### ISSUE THREAD

**Issue by Godkillme** [slimkit/plus#704]
版本：2.3
【PC端】进入某个具体的圈子，右侧“圈子成员”——“更多圈子成员”，页面显示不正常。
![bug](https://user-images.githubusercontent.com/33575502/54660923-3eb4aa00-4b13-11e9-9bb7-c6e9b44a4e49.jpg)

**Comment by mutoe** [comment]
已修复，感谢反馈
