### ISSUE TITLE
【PC-bug】动态列表多张GIF同时播放，没有按照顺序播放

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#707]
## 服务器
正式服

## 浏览器
Safari

## 描述
动态存在多张GIF时，所有GIF图片同时播放，与需求不符

## 预期
按照顺序依次播放

**Comment by maanrry** [comment]
并播放是GIF标识没有消失，（如第一张图为gif，在播放的时候gif没有消失）
期望：
播放时无gif标识
