### ISSUE TITLE
【pc-bug】文章详情页举报他人的评论是提示内容不存在

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#728]
## 服务器
正式服
## 描述
文章详情页举报他人的评论是提示内容不存在
## 配图
![image](https://user-images.githubusercontent.com/30249193/56259948-91c84f80-6107-11e9-899c-45365e2892fe.png)
## 期望
可以举报成功

**Comment by maanrry** [comment]
@boxshadow  未修复

**Comment by zhiyicx** [comment]
@maanrry 清除浏览器缓存后再试
