### ISSUE TITLE
【pc-bug】通知和评论我的一直处于加载中（特殊账号）

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus#762]
## 服务器
正式服
## 浏览器
谷歌
## 描述
账号：13808069927  123456
通知和评论我的一直处于加载中（特殊账号）

**Comment by LMTcancan** [comment]
测试服也是如此，账号同上，报错500
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/25689097/59001387-ed2dd880-8840-11e9-90d9-140f4cd936a0.png">
