### ISSUE TITLE
有时候“动态”的“话题”关注不了

### ISSUE THREAD

**Issue by mickeysu** [slimkit/plus#771]
有时候动态的话题关注不了，chrome返回500：
xhr.js:178   PUT http://localhost/api/v2/user/feed-topics/1 500 (Internal Server Error)
vue.runtime.esm.js:1888    Error: Request failed with status code 500

在phpstorm的debug调试提示服务端程序TopicFollow.php的follow()方法的语句：
         $link = $topic->users()->wherePivot('user_id', $user->id)->pivot;
出现对null对象访问属性的错误，数据库feed_topic_user_links确实也不存在对应“话题id”、“用户id”。
不过将上述代码增加firstOrCreate之后，“话题”能正常关注了：
$link = $topic->users()->wherePivot('user_id', $user->id)->firstOrCreate(['following_at' => new Carbon()])->pivot;

**Comment by boxshadow** [comment]
收到, 判断不严谨造成的问题
