### ISSUE TITLE
在圈子成员名单点击几位不同的成员进入个人主页时，有时个人主页不能加载动态列表

### ISSUE THREAD

**Issue by mickeysu** [slimkit/plus#772]
在圈子成员名单点击几位不同的成员进入个人主页时，有时个人主页不能加载动态列表。
如图所示，个人主页显示有“9条动态”，但“9条动态”提示下方的动态列表缺是空空的：
<img width="451" alt="屏幕快照 2019-05-28 12 17 54" src="https://user-images.githubusercontent.com/41137373/58450782-051ba300-8143-11e9-8517-777fdf139ce0.png">
<img width="449" alt="屏幕快照 2019-05-28 12 17 41" src="https://user-images.githubusercontent.com/41137373/58450783-077dfd00-8143-11e9-80ef-401c208a00d0.png">

我摸索了一下，在page/UserHome.vue如下代码中插入“this.fetchFeeding = false”这行代码，经调试发现可以解决问题：
      this.$http
        .get('/feeds', {
          params,
        })
        .then(({ data: { feeds = [] } }) => {
          this.fetchFeeding = false // ******修改BUG所新增的一行代码
          this.feeds = loadmore ? [...this.feeds, ...feeds] : feeds
          this.$refs.portal.afterLoadMore(feeds.length < params.limit)
        })
        .finally(() => {
          this.$refs.portal.afterUpdate()
        })

**Comment by mutoe** [comment]
添加在finally块中更佳

https://github.com/slimkit/plus/blob/66a85de9528d0cae6fcb94fc4fb001a210ac84ba/resources/spa/src/page/UserHome.vue#L376-L387
