### ISSUE TITLE
【admin-优化】认证管理-编辑，编辑认证信息时没有带入原有信息

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#779]
## 服务器
测试服

## 描述
编辑认证信息时没有带入原有信息

## 配图
<img width="994" alt="image" src="https://user-images.githubusercontent.com/25689097/59004196-75b17680-884b-11e9-9de9-caca5889b946.png">
<img width="821" alt="image" src="https://user-images.githubusercontent.com/25689097/59004209-7c3fee00-884b-11e9-9839-b20329dbe1bf.png">

## 预期
编辑页面带入原有信息

**Comment by boxshadow** [comment]
2.3版本已修复, 即将合并

**Comment by maanrry** [comment]
已修复
