### ISSUE TITLE
【pc-bug】消息-收到的赞，收到点赞时没有小红点消息提示

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#782]
## 服务器
测试服

## 操作
1. 用户A发布动态
2. 用户B进入最新动态列表，给用户A发布的动态点赞
3. 用户A查看消息-收到的赞

## 结果
缺少小红点，但收到的赞列表存在用户B的点赞数据

## 预期
收到点赞消息，未查看时显示小红点

**Comment by LMTcancan** [comment]
收到的评论也是如此

**Comment by boxshadow** [comment]
@LMTcancan 关于小红点,在重度修改

**Comment by maanrry** [comment]
已修复
