### ISSUE TITLE
【pc-优化】问答-提问，发布问题时设置悬赏描述需要更改

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#786]
## 服务器
正式服

## 描述
1. 发布问题时，将“金额”改为“积分”
2. 已设置悬赏的问题详情，将“金额”改为“积分”
3. 已设置悬赏的问题详情，将“¥”符号改为积分图标

## 配图
<img width="795" alt="image" src="https://user-images.githubusercontent.com/25689097/59186932-c0622400-8ba6-11e9-96c7-86e6d5ac7a6e.png">

<img width="681" alt="image" src="https://user-images.githubusercontent.com/25689097/59187837-ee486800-8ba8-11e9-936f-0f7f430218f3.png">

## 预期
<img width="375" alt="image" src="https://user-images.githubusercontent.com/25689097/59187877-002a0b00-8ba9-11e9-9c1e-8833abecfd48.png">

**Comment by maanrry** [comment]
已修复
