### ISSUE TITLE
【admin-bug】后台-认证管理-添加认证，输入用户ID占位文字写成输入用户名

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#808]
## 浏览器
Safari

## 服务器
正式服

## 描述
输入用户ID占位文字写成输入用户名

## 配图
<img width="780" alt="image" src="https://user-images.githubusercontent.com/25689097/61763807-583f6880-ae09-11e9-9a3b-fb2dc541a24a.png">

**Comment by boxshadow** [comment]
@LMTcancan 这里是输入用户名,搜索
