### ISSUE TITLE
【pc-bug】消息-系统通知：圈主收到帖子评论举报通知，消息列表显示为空

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus#820]
## 服务器
正式服

## 浏览器
Safari

## 描述
前提：后台设置圈子举报由圈主处理
圈主收到帖子评论举报通知，消息列表显示为空
账号：13808069927    123456
圈子：美图

## 配图
<img width="446" alt="image" src="https://user-images.githubusercontent.com/25689097/62517919-f34d2f00-b85a-11e9-9996-a3d003b955ea.png">

## 预期
<img width="279" alt="image" src="https://user-images.githubusercontent.com/25689097/62517965-07912c00-b85b-11e9-8052-b4fb29f9afd2.png">

**Comment by boxshadow** [comment]
@LMTcancan 已修复，并更新
