### ISSUE TITLE
【plus > 2.1 SPA设置】

### ISSUE THREAD

**Issue by penglitao** [slimkit/plus#821]
slimkit/plus-small-screen-client  官方介绍 该 仓库已经合并到 plus ，仅支持 plus <= 2.1 的下载使用，请问 plus > 2.1  的版本如何启用

**Comment by boxshadow** [comment]
@penglitao 已经移除了2.1版本, 建议使用 2.3+版本

**Comment by penglitao** [comment]
目前我的plus 版本是 2.3.1  ，那我还需要安装 slimkit/plus-small-screen-client 这个仓库吗，我看说明是已经包含的

那么，plus 2.3.1 如何 该模块呢




在 2019-08-08 10:25:10，"boxshadow" <notifications@github.com> 写道：


@penglitao 已经移除了2.1版本, 建议使用 2.3+版本

**Comment by boxshadow** [comment]
> 目前我的plus 版本是 2.3.1 ，那我还需要安装 slimkit/plus-small-screen-client 这个仓库吗，我看说明是已经包含的 那么，plus 2.3.1 如何 该模块呢 在 2019-08-08 10:25:10，"boxshadow" <notifications@github.com> 写道： @penglitao 已经移除了2.1版本, 建议使用 2.3+版本 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

不需要再安装这个模块， spa已经集成到主库中， 源码位于 resources/spa中
