### ISSUE TITLE
【IOS-bug】TS+3后台关闭微信支付，IOS APP没有隐藏微信支付

### ISSUE THREAD

**Issue by zuoaihua** [slimkit/plus#825]
后台：配置/支付配置/支付方式开关
取消微信支付选项

IOS端仍然显示微信支付选项，并且可以操作
IOS APP--发现--积分任务--充值
![IOS 微信支付](https://user-images.githubusercontent.com/40266775/62820177-15182000-bb93-11e9-9f9c-bb44a0c5a577.jpg)

**Comment by boxshadow** [comment]
![1565693568782](https://user-images.githubusercontent.com/8577474/62988121-bd6d0380-be75-11e9-8dc6-9e1c9bac9f7b.jpg)
@zuoaihua 请根据上图的方式 清理一下数据缓存，
并且需要app也需要清理一下配置缓存
因为这些内容不是需要频繁修改的配置项，所有做了缓存处理
