### ISSUE TITLE
【pc-bug】没有定义 /api/v2/questions 路由

### ISSUE THREAD

**Issue by meiyoufengzhengdexian** [slimkit/plus#831]
在这个文件里： /thinksns-plus/packages/zhiyicx-plus-pc/src/ViewComposers/HotQuestions.php

前台 /thinksns-plus/packages/zhiyicx-plus-pc/resources/views/widgets/hotquestions.blade.php  报$issue['id'] 找不到

**Comment by boxshadow** [comment]
@meiyoufengzhengdexian 开源版是没有圈子和问答应用的
