### ISSUE TITLE
/installer 404

### ISSUE THREAD

**Issue by AirCrayon** [slimkit/plus#835]
按照文档的安装步骤 /installer 404

**Comment by boxshadow** [comment]
@AirCrayon 由于诸多原因，安装程序移除了

**Comment by weisnc** [comment]
现在如何安装？

**Comment by weisnc** [comment]
> @AirCrayon 由于诸多原因，安装程序移除了

现在如何安装？

**Comment by uussoft** [comment]
不开源就不要开源，不要打着开源的幌子干不开源的事，不开源没有人会说你们，打着开源的幌子那就有问题了

**Comment by uussoft** [comment]
那现在该如何安装呢？

**Comment by uussoft** [comment]
或者需要配置哪些信息可以让系统正常运行？
