### ISSUE TITLE
{type: bug, version: 2.3.0}: vendor文件夹下载不下来

### ISSUE THREAD

**Issue by cxl769807768** [slimkit/plus#843]
## 基本信息

版本：`2.3.0`

## 重现步骤

composer install下载不了vendor文件夹，如果国内镜像没有相关包的话，肯定是很难下载下来的

## 补充说明（可选）

PHP 版本：
数据库类型：
数据库版本：

**Comment by appmakerpeng** [comment]
我也是 直接下载下来没有vendor文件夹

**Comment by boxshadow** [comment]
@cxl769807768 @appmakerpeng 
可以提供一下具体无法安装的依赖或者安装依赖时的报错
